import express from 'express';
import { registerUser, loginUser, updateUserSettings, getUserProfile } from '../controllers/authController.js';
import protect from '../middleware/authMiddleware.js';
import { googleLogin } from '../controllers/authController.js';
const router = express.Router();
router.post('/register', registerUser);
router.post('/login', loginUser);
router.post('/google', googleLogin);
router.get('/profile', protect, getUserProfile);
router.put('/update-settings', protect, updateUserSettings);
export default router;