// HSN Codes - Part 3: Chapters 85–99 + SAC Codes (Services)
const hsnData3 = [
  // Chapter 85 - Electrical machinery and equipment
  { code: "8501", description: "Electric motors and generators (excluding generating sets)" },
  { code: "8502", description: "Electric generating sets and rotary converters" },
  { code: "8503", description: "Parts suitable for use solely or principally with the machines of heading 8501 or 8502" },
  { code: "8504", description: "Electrical transformers, static converters (for example, rectifiers) and inductors" },
  { code: "8505", description: "Electromagnets; permanent magnets and articles intended to become permanent magnets after magnetisation; electromagnetic or permanent magnet chucks, clamps and similar holding devices; electromagnetic couplings, clutches and brakes; electromagnetic lifting heads" },
  { code: "8506", description: "Primary cells and primary batteries" },
  { code: "8507", description: "Electric accumulators (storage batteries), including separators therefor, whether or not rectangular (including square)" },
  { code: "8508", description: "Vacuum cleaners" },
  { code: "8509", description: "Electro-mechanical domestic appliances, with self-contained electric motor, other than vacuum cleaners of heading 8508" },
  { code: "8510", description: "Shavers, hair clippers and hair-removing appliances, with self-contained electric motor" },
  { code: "8511", description: "Electrical ignition or starting equipment of a kind used for spark-ignition or compression-ignition internal combustion engines" },
  { code: "8512", description: "Electrical lighting or signalling equipment (excluding articles of heading 8539), windscreen wipers, defrosters and demisters, of a kind used for cycles or motor vehicles" },
  { code: "8513", description: "Portable electric lamps designed to function by their own source of energy (for example, dry batteries, accumulators, magnetos), other than lighting equipment of heading 8512" },
  { code: "8514", description: "Industrial or laboratory electric furnaces and ovens (including those functioning by induction or dielectric loss); other industrial or laboratory equipment for the heat treatment of materials by induction or dielectric loss" },
  { code: "8515", description: "Electric (including electrically heated gas), laser or other light or photon beam, ultrasonic, electron beam, magnetic pulse or plasma arc soldering, brazing or welding machines and apparatus" },
  { code: "8516", description: "Electric instantaneous or storage water heaters and immersion heaters; electric space heating apparatus and soil heating apparatus; electrothermic hair-dressing apparatus (for example, hair dryers, hair curlers, curling tong heaters) and hand dryers; electric flatirons; other electrothermic appliances of a kind used for domestic purposes; electric heating resistors, other than those of heading 8545" },
  { code: "8517", description: "Telephone sets, including telephones for cellular networks or for other wireless networks; other apparatus for the transmission or reception of voice, images or other data, including apparatus for communication in a wired or wireless network (such as a local or wide area network), other than transmission or reception apparatus of heading 8443, 8525, 8527 or 8528 (mobile phones, smartphones)" },
  { code: "8518", description: "Microphones and stands therefor; loudspeakers, whether or not mounted in their enclosures; headphones and earphones, whether or not combined with a microphone, and sets consisting of a microphone and one or more loudspeakers; audio-frequency electric amplifiers; electric sound amplifier sets" },
  { code: "8519", description: "Sound recording or reproducing apparatus" },
  { code: "8521", description: "Video recording or reproducing apparatus, whether or not incorporating a video tuner" },
  { code: "8522", description: "Parts and accessories suitable for use solely or principally with the apparatus of headings 8519 to 8521" },
  { code: "8523", description: "Discs, tapes, solid-state non-volatile storage devices, smart cards and other media for the recording of sound or of other phenomena, whether or not recorded, including matrices and masters for the production of discs, but excluding products of Chapter 37" },
  { code: "8524", description: "Flat panel display modules, whether or not incorporating touch screens" },
  { code: "8525", description: "Transmission apparatus for radio-broadcasting or television, whether or not incorporating reception apparatus or sound recording or reproducing apparatus; television cameras, digital cameras and video camera recorders" },
  { code: "8526", description: "Radar apparatus, radio navigational aid apparatus and radio remote control apparatus" },
  { code: "8527", description: "Reception apparatus for radio-broadcasting, whether or not combined in the same housing with sound recording or reproducing apparatus or a clock" },
  { code: "8528", description: "Monitors and projectors, not incorporating television reception apparatus; reception apparatus for television, whether or not incorporating radio-broadcast receivers or sound or video recording or reproducing apparatus" },
  { code: "8529", description: "Parts suitable for use solely or principally with the apparatus of headings 8524 to 8528" },
  { code: "8530", description: "Electrical signalling, safety or traffic control equipment for railways, tramways, roads, inland waterways, parking facilities, port installations or airfields" },
  { code: "8531", description: "Electric sound or visual signalling apparatus (for example, bells, sirens, indicator panels, burglar or fire alarms), other than those of heading 8512 or 8530" },
  { code: "8532", description: "Electrical capacitors, fixed, variable or adjustable (pre-set)" },
  { code: "8533", description: "Electrical resistors (including rheostats and potentiometers), other than heating resistors" },
  { code: "8534", description: "Printed circuits" },
  { code: "8535", description: "Electrical apparatus for switching or protecting electrical circuits, or for making connections to or in electrical circuits (for example, switches, fuses, lightning arresters, voltage limiters, surge suppressors, plugs and junction boxes), for a voltage exceeding 1,000 V" },
  { code: "8536", description: "Electrical apparatus for switching or protecting electrical circuits, or for making connections to or in electrical circuits (for example, switches, relays, fuses, surge suppressors, plugs, sockets, lamp-holders and other connectors, junction boxes), for a voltage not exceeding 1,000 V; connectors for optical fibres, optical fibre bundles or cables" },
  { code: "8537", description: "Boards, panels, consoles, desks, cabinets and other bases, equipped with two or more apparatus of heading 8535 or 8536, for electric control or the distribution of electricity, including those incorporating instruments or apparatus of Chapter 90, and numerical control apparatus, other than switching apparatus of heading 8517" },
  { code: "8538", description: "Parts suitable for use solely or principally with the apparatus of heading 8535, 8536 or 8537" },
  { code: "8539", description: "Filament or discharge lamps, including sealed beam lamp units and ultraviolet or infra-red lamps; arc-lamps; light-emitting diode (LED) lamps" },
  { code: "8540", description: "Thermionic, cold cathode or photo-cathode valves and tubes (for example, vacuum or vapour or gas filled tubes, mercury arc rectifying tubes, cathode-ray tubes, television camera tubes)" },
  { code: "8541", description: "Semiconductor devices (for example, diodes, transistors, semiconductor-based transducers); photosensitive semiconductor devices, including photovoltaic cells whether or not assembled in modules or made up into panels; light emitting diodes (LED), whether or not assembled with other light emitting diodes (LED); mounted piezo-electric crystals" },
  { code: "8542", description: "Electronic integrated circuits" },
  { code: "8543", description: "Electrical machines and apparatus, having individual functions, not specified or included elsewhere in this Chapter" },
  { code: "8544", description: "Insulated (including enamelled or anodised) wire, cable (including co-axial cable) and other insulated electric conductors, whether or not fitted with connectors; optical fibre cables, made up of individually sheathed fibres, whether or not assembled with electric conductors or fitted with connectors" },
  { code: "8545", description: "Carbon electrodes, carbon brushes, lamp carbons, battery carbons and other articles of graphite or other carbon, with or without metal, of a kind used for electrical purposes" },
  { code: "8546", description: "Electrical insulators of any material" },
  { code: "8547", description: "Insulating fittings for electrical machines, appliances or equipment, being fittings wholly of insulating material apart from any minor components of metal (for example, threaded sockets) incorporated during moulding solely for the purposes of assembly, other than insulators of heading 8546; electrical conduit tubing and joints therefor, of base metal lined with insulating material" },
  { code: "8548", description: "Waste and scrap of primary cells, primary batteries and electric accumulators; spent primary cells, spent primary batteries and spent electric accumulators; electrical parts of machinery or apparatus, not specified or included elsewhere in this Chapter" },
  // Chapter 86 - Railway or tramway locomotives
  { code: "8601", description: "Rail locomotives powered from an external source of electricity or by electric accumulators" },
  { code: "8602", description: "Other rail locomotives; locomotive tenders" },
  { code: "8603", description: "Self-propelled railway or tramway coaches, vans and trucks, other than those of heading 8604" },
  { code: "8604", description: "Railway or tramway maintenance or service vehicles, whether or not self-propelled (for example, workshops, cranes, ballast tampers, trackliners, testing coaches and track inspection vehicles)" },
  { code: "8605", description: "Railway or tramway passenger coaches, not self-propelled; luggage vans, post office coaches and other special purpose railway or tramway coaches, not self-propelled (excluding those of heading 8604)" },
  { code: "8606", description: "Railway or tramway goods vans and wagons, not self-propelled" },
  { code: "8607", description: "Parts of railway or tramway locomotives or rolling-stock" },
  { code: "8608", description: "Railway or tramway track fixtures and fittings; mechanical (including electro-mechanical) signalling, safety or traffic control equipment for railways, tramways, roads, inland waterways, parking facilities, port installations or airfields" },
  { code: "8609", description: "Containers (including containers for the transport of fluids) specially designed and equipped for carriage by one or more modes of transport" },
  // Chapter 87 - Vehicles other than railway
  { code: "8701", description: "Tractors (other than tractors of heading 8709)" },
  { code: "8702", description: "Motor vehicles for the transport of ten or more persons, including the driver" },
  { code: "8703", description: "Motor cars and other motor vehicles principally designed for the transport of persons (other than those of heading 8702), including station wagons and racing cars" },
  { code: "8704", description: "Motor vehicles for the transport of goods" },
  { code: "8705", description: "Special purpose motor vehicles, other than those principally designed for the transport of persons or goods (for example, breakdown lorries, crane lorries, fire fighting vehicles, concrete-mixer lorries, road sweeper lorries, spraying lorries, mobile workshops, mobile radiological units)" },
  { code: "8706", description: "Chassis fitted with engines, for the motor vehicles of headings 8701 to 8705" },
  { code: "8707", description: "Bodies (including cabs), for the motor vehicles of headings 8701 to 8705" },
  { code: "8708", description: "Parts and accessories of the motor vehicles of headings 8701 to 8705" },
  { code: "8709", description: "Works trucks, self-propelled, not fitted with lifting or handling equipment, of the type used in factories, warehouses, dock areas or airports for short distance transport of goods" },
  { code: "8710", description: "Tanks and other armoured fighting vehicles, motorised, whether or not fitted with weapons, and parts of such vehicles" },
  { code: "8711", description: "Motorcycles (including mopeds) and cycles fitted with an auxiliary motor, with or without side-cars; side-cars" },
  { code: "8712", description: "Bicycles and other cycles (including delivery tricycles), not motorised" },
  { code: "8713", description: "Carriages for disabled persons, whether or not motorised or otherwise mechanically propelled" },
  { code: "8714", description: "Parts and accessories of vehicles of headings 8711 to 8713" },
  { code: "8715", description: "Baby carriages and parts thereof" },
  { code: "8716", description: "Trailers and semi-trailers; other vehicles, not mechanically propelled; parts thereof" },
  // Chapter 88-89 - Aircraft, spacecraft, ships
  { code: "8801", description: "Balloons and dirigibles; gliders, hang gliders and other non-powered aircraft" },
  { code: "8802", description: "Other aircraft (for example, helicopters, aeroplanes); spacecraft (including satellites) and suborbital and spacecraft launch vehicles" },
  { code: "8803", description: "Parts of goods of heading 8801 or 8802" },
  { code: "8804", description: "Parachutes (including dirigible parachutes and paragliders) and rotochutes; parts thereof and accessories thereto" },
  { code: "8901", description: "Cruise ships, excursion boats, ferry-boats, cargo ships, barges and similar vessels for the transport of persons or goods" },
  { code: "8902", description: "Fishing vessels; factory ships and other vessels for processing or preserving fishery products" },
  { code: "8903", description: "Yachts and other vessels for pleasure or sports; rowing boats and canoes" },
  { code: "8904", description: "Tugs and pusher craft" },
  { code: "8905", description: "Light-vessels, fire-floats, dredgers, floating cranes, and other vessels the navigability of which is subsidiary to their main function; floating docks; floating or submersible drilling or production platforms" },
  { code: "8906", description: "Other vessels, including warships and lifeboats other than rowing boats" },
  { code: "8907", description: "Other floating structures (for example, rafts, tanks, coffer-dams, landing-stages, buoys and beacons)" },
  { code: "8908", description: "Vessels and other floating structures for breaking up" },
  // Chapter 90 - Optical, photographic, cinematographic, measuring, checking instruments
  { code: "9001", description: "Optical fibres and optical fibre bundles; optical fibre cables other than those of heading 8544; sheets and plates of polarising material; lenses (including contact lenses), prisms, mirrors and other optical elements, of any material, unmounted" },
  { code: "9002", description: "Lenses, prisms, mirrors and other optical elements, of any material, mounted, being parts of or fittings for instruments or apparatus, other than such elements of glass not optically worked" },
  { code: "9003", description: "Frames and mountings for spectacles, goggles or the like, and parts thereof" },
  { code: "9004", description: "Spectacles, goggles and the like, corrective, protective or other" },
  { code: "9005", description: "Binoculars, monoculars, other optical telescopes, and mountings therefor; other astronomical instruments and mountings therefor, but not including instruments for radio-astronomy" },
  { code: "9006", description: "Photographic (other than cinematographic) cameras; photographic flashlight apparatus and flashbulbs other than discharge lamps of heading 8539" },
  { code: "9007", description: "Cinematographic cameras and projectors, whether or not incorporating sound recording or reproducing apparatus" },
  { code: "9008", description: "Image projectors, other than cinematographic; photographic (other than cinematographic) enlargers and reducers" },
  { code: "9010", description: "Apparatus and equipment for photographic (including cinematographic) laboratories, not specified or included elsewhere in this Chapter; negatoscopes; projection screens" },
  { code: "9011", description: "Compound optical microscopes, including those for photomicrography, cinephotomicrography or microprojection" },
  { code: "9012", description: "Microscopes other than optical microscopes; diffraction apparatus" },
  { code: "9013", description: "Liquid crystal devices not constituting articles provided for more specifically in other headings; lasers, other than laser diodes; other optical appliances and instruments, not specified or included elsewhere in this Chapter" },
  { code: "9014", description: "Direction finding compasses; other navigational instruments and appliances" },
  { code: "9015", description: "Surveying (including photogrammetrical surveying), hydrographic, oceanographic, hydrological, meteorological or geophysical instruments and appliances, excluding compasses" },
  { code: "9016", description: "Balances of a sensitivity of 5 cg or better, with or without weights" },
  { code: "9017", description: "Drawing, marking-out or mathematical calculating instruments (for example, drafting machines, pantographs, protractors, drawing sets, slide rules, disc calculators)" },
  { code: "9018", description: "Instruments and appliances used in medical, surgical, dental or veterinary sciences, including scintigraphic apparatus, other electro-medical apparatus and sight-testing instruments" },
  { code: "9019", description: "Mechano-therapy appliances; massage apparatus; psychological aptitude-testing apparatus; ozone therapy, oxygen therapy, aerosol therapy, artificial respiration or other therapeutic respiration apparatus" },
  { code: "9020", description: "Other breathing appliances and gas masks, excluding protective masks having neither mechanical parts nor replaceable filters" },
  { code: "9021", description: "Orthopaedic appliances, including crutches, surgical belts and trusses; splints and other fracture appliances; artificial parts of the body; hearing aids and other appliances which are worn or carried, or implanted in the body, to compensate for a defect or disability" },
  { code: "9022", description: "Apparatus based on the use of X-rays or of alpha, beta, gamma or other ionising radiations, whether or not for medical, surgical, dental or veterinary uses" },
  { code: "9023", description: "Instruments, apparatus and models, designed for demonstrational purposes (for example, in education or exhibitions), unsuitable for other uses" },
  { code: "9024", description: "Machines and appliances for testing the hardness, strength, compressibility, elasticity or other mechanical properties of materials (for example, metals, wood, textiles, paper, plastics)" },
  { code: "9025", description: "Hydrometers and similar floating instruments, thermometers, pyrometers, barometers, hygrometers and psychrometers, recording or not, and any combination of these instruments" },
  { code: "9026", description: "Instruments and apparatus for measuring or checking the flow, level, pressure or other variables of liquids or gases (for example, flow meters, level gauges, manometers, heat meters), excluding instruments and apparatus of heading 9014, 9015, 9028 or 9032" },
  { code: "9027", description: "Instruments and apparatus for physical or chemical analysis (for example, polarimeters, refractometers, spectrometers, gas or smoke analysis apparatus)" },
  { code: "9028", description: "Gas, liquid or electricity supply or production meters, including calibrating meters therefor" },
  { code: "9029", description: "Revolution counters, production counters, taximeters, milometers, pedometers and the like; speed indicators and tachometers, other than those of heading 9014 or 9015" },
  { code: "9030", description: "Oscilloscopes, spectrum analysers and other instruments and apparatus for measuring or checking electrical quantities, excluding meters of heading 9028" },
  { code: "9031", description: "Measuring or checking instruments, appliances and machines, not specified or included elsewhere in this Chapter; profile projectors" },
  { code: "9032", description: "Automatic regulating or controlling instruments and apparatus" },
  { code: "9033", description: "Parts and accessories (not specified or included elsewhere in this Chapter) for machines, appliances, instruments or apparatus of Chapter 90" },
  // Chapter 91 - Clocks and watches
  { code: "9101", description: "Wrist-watches, pocket-watches and other watches, including stop-watches, with case of precious metal or of metal clad with precious metal" },
  { code: "9102", description: "Wrist-watches, pocket-watches and other watches, including stop-watches, other than those of heading 9101" },
  { code: "9103", description: "Clocks with watch movements, excluding clocks of heading 9104" },
  { code: "9104", description: "Instrument panel clocks and clocks of a similar type for vehicles, aircraft, spacecraft or vessels" },
  { code: "9105", description: "Other clocks" },
  { code: "9108", description: "Watch movements, complete and assembled" },
  { code: "9109", description: "Clock movements, complete and assembled" },
  { code: "9110", description: "Complete watch or clock movements, unassembled or partly assembled (movement sets); incomplete watch or clock movements, assembled; rough watch or clock movements" },
  { code: "9111", description: "Watch cases and parts thereof" },
  { code: "9112", description: "Clock cases and cases of a similar type for other goods of this Chapter, and parts thereof" },
  { code: "9113", description: "Watch straps, watch bands and watch bracelets, and parts thereof" },
  { code: "9114", description: "Other clock or watch parts" },
  // Chapter 92 - Musical instruments
  { code: "9201", description: "Pianos, including automatic pianos; harpsichords and other keyboard stringed instruments" },
  { code: "9202", description: "Other string musical instruments (for example, guitars, violins, harps)" },
  { code: "9205", description: "Wind musical instruments (for example, keyboard pipe organs, accordions, clarinets, trumpets, bagpipes), other than fairground organs and mechanical street organs" },
  { code: "9206", description: "Percussion musical instruments (for example, drums, xylophones, cymbals, castanets, maracas)" },
  { code: "9207", description: "Musical instruments, the sound of which is produced, or must be amplified, electrically (for example, organs, guitars, accordions)" },
  { code: "9208", description: "Musical boxes, fairground organs, mechanical street organs, mechanical singing birds, musical saws and other musical instruments not falling within any other heading of this Chapter; decoy calls of all kinds; whistles, call horns and other mouth-blown sound signalling instruments" },
  { code: "9209", description: "Parts (for example, mechanisms for musical boxes) and accessories (for example, cards, discs and rolls for mechanical instruments) of musical instruments; metronomes, tuning forks and pitch pipes of all kinds" },
  // Chapter 94 - Furniture; bedding, mattresses; lamps and lighting fittings
  { code: "9401", description: "Seats (other than those of heading 9402), whether or not convertible into beds, and parts thereof" },
  { code: "9402", description: "Medical, surgical, dental or veterinary furniture (for example, operating tables, examination tables, hospital beds with mechanical fittings, dentists chairs)" },
  { code: "9403", description: "Other furniture and parts thereof" },
  { code: "9404", description: "Mattress supports; articles of bedding and similar furnishing (for example, mattresses, quilts, eiderdowns, cushions, pouffes and pillows) fitted with springs or stuffed or internally fitted with any material or of cellular rubber or plastics, whether or not covered" },
  { code: "9405", description: "Lamps and lighting fittings including searchlights and spotlights and parts thereof, not elsewhere specified or included; illuminated signs, illuminated name-plates and the like, having a permanently fixed light source, and parts thereof not elsewhere specified or included" },
  { code: "9406", description: "Prefabricated buildings" },
  // Chapter 95 - Toys, games and sports requisites
  { code: "9503", description: "Tricycles, scooters, pedal cars and similar wheeled toys; dolls carriages; dolls; other toys; reduced-scale (scale) models and similar recreational models, working or not; puzzles of all kinds" },
  { code: "9504", description: "Video game consoles and machines, articles for funfair, table or parlour games, including pintables, billiards, special tables for casino games and automatic bowling alley equipment" },
  { code: "9505", description: "Festive, carnival or other entertainment articles, including conjuring tricks and novelty jokes" },
  { code: "9506", description: "Articles and equipment for general physical exercise, gymnastics, athletics, other sports (including table-tennis) or outdoor games, not specified or included elsewhere in this Chapter" },
  { code: "9507", description: "Fishing rods, fish-hooks and other line fishing tackle; fish landing nets, butterfly nets and similar nets; decoy birds (other than those of heading 9208 or 9705) and similar hunting or shooting requisites" },
  { code: "9508", description: "Roundabouts, swings, shooting galleries and other fairground amusements; travelling circuses and travelling menageries; travelling theatres" },
  // Chapter 96 - Miscellaneous manufactured articles
  { code: "9601", description: "Worked ivory, bone, tortoise-shell, horn, antlers, coral, mother-of-pearl and other animal carving material, and articles of these materials (including articles obtained by moulding)" },
  { code: "9602", description: "Worked vegetable or mineral carving material and articles of these materials; moulded or carved articles of wax, of stearin, of natural gums or natural resins or of modelling pastes, and other moulded or carved articles, not elsewhere specified or included; worked, unhardened gelatin (except gelatin of heading 3503) and articles of unhardened gelatin" },
  { code: "9603", description: "Brooms, brushes (including brushes constituting parts of machines, appliances or vehicles), hand-operated mechanical floor sweepers, not motorised, mops and feather dusters; prepared knots and tufts for broom or brush making; paint pads and rollers; squeegees (other than roller squeegees)" },
  { code: "9604", description: "Hand sieves and hand riddles" },
  { code: "9605", description: "Travel sets for personal toilet, sewing or shoe or clothes cleaning" },
  { code: "9606", description: "Buttons, press-fasteners, snap-fasteners and press-studs, button moulds and other parts of these articles; button blanks" },
  { code: "9607", description: "Slide fasteners and parts thereof" },
  { code: "9608", description: "Ball point pens; felt tipped and other porous-tipped pens and markers; fountain pens, stylograph pens and other pens; duplicating stylos; propelling or sliding pencils; pen-holders, pencil-holders and similar holders; parts (including caps and clips) of the foregoing articles, other than those of heading 9609" },
  { code: "9609", description: "Pencils (other than pencils of heading 9608), crayons, pencil leads, pastels, drawing charcoals, writing or drawing chalks and tailors chalks" },
  { code: "9610", description: "Slates and boards, with writing or drawing surfaces, whether or not framed" },
  { code: "9611", description: "Date, sealing or numbering stamps, and the like (including devices for printing or embossing labels), designed for operating in the hand; hand-operated composing sticks and hand printing sets incorporating such composing sticks" },
  { code: "9612", description: "Typewriter or similar ribbons, inked or otherwise prepared for giving impressions, whether or not on spools or in cartridges; ink-pads, whether or not inked, with or without boxes" },
  { code: "9613", description: "Cigarette lighters and other lighters, whether or not mechanical or electrical, and parts thereof other than flints and wicks" },
  { code: "9614", description: "Smoking pipes (including pipe bowls) and cigar or cigarette holders, and parts thereof" },
  { code: "9615", description: "Combs, hair-slides and the like; hairpins, curling pins, curling grips, hair-curlers and the like, other than those of heading 8516, and parts thereof" },
  { code: "9616", description: "Scent sprays and similar toilet sprays, and mounts and heads therefor; powder-puffs and pads for the application of cosmetics or toilet preparations" },
  { code: "9617", description: "Vacuum flasks and other vacuum vessels, complete with cases; parts thereof other than glass inners" },
  { code: "9618", description: "Tailors dummies and other lay figures; automata and other animated displays used for shop window dressing" },
  { code: "9619", description: "Sanitary towels (pads) and tampons, napkins and napkin liners for babies and similar articles, of any material" },
  // Chapter 97 - Works of art, collectors pieces and antiques
  { code: "9701", description: "Paintings, drawings and pastels, executed entirely by hand, other than drawings of heading 4906 and other than hand-painted or hand-decorated manufactured articles; collages and similar decorative plaques" },
  { code: "9702", description: "Original engravings, prints and lithographs" },
  { code: "9703", description: "Original sculptures and statuary, in any material" },
  { code: "9704", description: "Postage or revenue stamps, stamp-postmarks, first-day covers, postal stationery (stamped paper), and the like, used or unused, other than those of heading 4907" },
  { code: "9705", description: "Collections and collectors pieces of zoological, botanical, mineralogical, anatomical, historical, archaeological, palaeontological, ethnographic or numismatic interest" },
  { code: "9706", description: "Antiques of an age exceeding one hundred years" },
  // ── SAC CODES (Services) ──────────────────────────────────────────────────────
  // Section 5 - Construction Services
  { code: "9954", description: "Construction services" },
  { code: "995411", description: "Construction services of single dwelling or multi dwelling or multi-storied residential buildings" },
  { code: "995412", description: "Construction services of other residential buildings such as old age homes, homeless shelters, hostels etc." },
  { code: "995413", description: "Construction services of industrial buildings such as factories, workshops etc." },
  { code: "995414", description: "Construction services of commercial buildings such as office buildings, exhibition & marriage halls, malls/shopping complex etc." },
  { code: "995415", description: "Construction services of other non-residential buildings such as educational institutions, hospitals etc." },
  { code: "995416", description: "Construction services of other buildings" },
  { code: "995419", description: "Services involving repair, alterations, additions, replacements, renovation, maintenance or remodelling of the buildings" },
  { code: "995421", description: "General construction services of highways, streets, roads, railways and airfield runways, bridges and tunnels" },
  { code: "995422", description: "General construction services of harbours, waterways, dams, water mains and lines, irrigation and other waterworks" },
  { code: "995423", description: "General construction services of long-distance underground/ overground/ submarine pipelines, communication and electric power lines (cables); pumping stations and related works" },
  { code: "995424", description: "General construction services of local water & sewage pipelines, electricity and communication cables & related works" },
  { code: "995425", description: "General construction services of mines and industrial plants" },
  { code: "995426", description: "Construction services of power plants and its related infrastructure" },
  { code: "995427", description: "Construction services of other civil engineering works" },
  // Section 6 - Wholesale/Retail Trade Services
  { code: "9961", description: "Services in wholesale trade" },
  { code: "9962", description: "Services in retail trade" },
  // Section 7 - Land Transport Services
  { code: "9964", description: "Passenger transport services" },
  { code: "996411", description: "Road transport services of passengers" },
  { code: "996412", description: "Taxi services including radio taxi & other similar services" },
  { code: "996413", description: "Non-scheduled local bus and coach charter services" },
  { code: "996414", description: "Other land transportation services of passengers" },
  { code: "996421", description: "Railway transport services of passengers" },
  { code: "996422", description: "Metro rail and monorail services" },
  { code: "996431", description: "Coastal and transoceanic water transport services of passengers" },
  { code: "996441", description: "Domestic air transport services of passengers" },
  { code: "996442", description: "International air transport services of passengers" },
  { code: "9965", description: "Goods transport services" },
  { code: "996511", description: "Road transport services of goods including letters, parcels, live animals, household & office furniture, containers etc." },
  { code: "996512", description: "Railway transport services of goods including letters, parcels, live animals, household & office furniture, containers etc." },
  { code: "996513", description: "Transport services of petroleum and natural gas, other than pipeline transport services" },
  { code: "996521", description: "Domestic water transport services of goods" },
  { code: "996522", description: "International water transport services of goods" },
  { code: "996531", description: "Domestic air transport services of goods" },
  { code: "996532", description: "International air transport services of goods" },
  // Section 8 - Accommodation, Food and Beverage Services
  { code: "9963", description: "Accommodation, food and beverage services" },
  { code: "996311", description: "Room or unit accommodation services provided by Hotels, INN, Guest House, Club etc." },
  { code: "996312", description: "Camp site services" },
  { code: "996313", description: "Recreational and vacation camp services" },
  { code: "996321", description: "Room or unit accommodation services for students in student residences" },
  { code: "996322", description: "Room or unit accommodation services provided by Hostels, Dormitories, Boarding Houses" },
  { code: "996329", description: "Other similar services" },
  { code: "996331", description: "Services provided by Restaurants, Cafes and similar eating facilities including takeaway services, room services and door delivery of food" },
  { code: "996332", description: "Services provided by Hotels to guests" },
  { code: "996333", description: "Services provided in Canteen and other similar establishments" },
  { code: "996334", description: "Catering Services in Exhibition halls, Events, Marriage Halls and other outdoor/indoor functions" },
  { code: "996335", description: "Catering Services in trains, flights etc." },
  { code: "996336", description: "Preparation and/or supply services of food, edible preparations, alcoholic & non-alcoholic beverages to airlines and other transportation operators" },
  // Section 9 - Financial and Insurance Services
  { code: "9971", description: "Financial and related services" },
  { code: "997111", description: "Central banking services" },
  { code: "997112", description: "Deposit services" },
  { code: "997113", description: "Credit-granting services including stand-by commitment, guarantees & letters of credit" },
  { code: "997114", description: "Financial leasing services" },
  { code: "997115", description: "Hire-purchase-type services" },
  { code: "997116", description: "Securities and commodity contracts brokerage and related services" },
  { code: "997117", description: "Portfolio management services" },
  { code: "997118", description: "Trust and custody services" },
  { code: "997119", description: "Financial advisory and intermediation services" },
  { code: "997120", description: "Payment services" },
  { code: "997132", description: "Life insurance services (excluding reinsurance services)" },
  { code: "997133", description: "Accident and health insurance services" },
  { code: "997134", description: "Motor vehicle insurance services" },
  { code: "997135", description: "Marine, aviation, and other transport insurance services" },
  { code: "997136", description: "Freight insurance services and travel insurance services" },
  { code: "997137", description: "Other property insurance services" },
  { code: "997141", description: "Pension fund management services" },
  // Section 10 - Real Estate Services
  { code: "9972", description: "Real estate services" },
  { code: "997211", description: "Rental or leasing services involving own or leased residential property" },
  { code: "997212", description: "Rental or leasing services involving own or leased non-residential property" },
  { code: "997213", description: "Trade services of buildings" },
  { code: "997214", description: "Trade services of time-share properties" },
  { code: "997221", description: "Property management services on a fee/commission basis for residential properties" },
  { code: "997222", description: "Property management services on a fee/commission basis for non-residential properties" },
  // Section 11 - Rental and Leasing Services
  { code: "9973", description: "Leasing or rental services without operator" },
  { code: "997311", description: "Financial leasing services of transport equipment including motor vehicles, aircraft, vessels" },
  { code: "997312", description: "Leasing of transport equipment without operators - aircraft" },
  { code: "997313", description: "Leasing of commercial and industrial machinery and equipment without operators" },
  { code: "997314", description: "Leasing of agricultural machinery and equipment without operators" },
  { code: "997315", description: "Leasing of construction machinery and equipment without operators" },
  { code: "997316", description: "Leasing of office machinery and equipment including computers without operators" },
  { code: "997319", description: "Leasing or rental services concerning other machinery and equipments without operators" },
  { code: "997321", description: "Leasing or rental services of furniture and other household appliances" },
  // Section 12 - Professional, Technical and Business Services
  { code: "9983", description: "Other professional, technical and business services" },
  { code: "998311", description: "Management consulting and management services including financial, strategic, human resources, marketing, operations and supply chain areas" },
  { code: "998312", description: "Business consulting services including public relations services" },
  { code: "998313", description: "Information technology consulting and support services" },
  { code: "998314", description: "Information technology (IT) infrastructure provisioning services" },
  { code: "998315", description: "Information technology (IT) consulting and support services" },
  { code: "998316", description: "Support services to agriculture, forestry, fishing, mining and utilities" },
  { code: "998317", description: "Building-cleaning services" },
  { code: "998318", description: "Other support services" },
  { code: "998319", description: "Other professional, technical and business services" },
  { code: "998321", description: "Architectural services" },
  { code: "998322", description: "Urban planning and landscape architectural services" },
  { code: "998323", description: "Engineering advisory services" },
  { code: "998324", description: "Engineering services for industrial and manufacturing processes" },
  { code: "998325", description: "Other engineering services" },
  { code: "998326", description: "Technical inspection, analysis and certification services" },
  { code: "998331", description: "Research and experimental development services in natural sciences" },
  { code: "998332", description: "Research and experimental development services in engineering and technology" },
  { code: "998333", description: "Research and experimental development services in social sciences and humanities" },
  { code: "998334", description: "Interdisciplinary research and experimental development services" },
  { code: "998341", description: "Accounting and book-keeping services" },
  { code: "998342", description: "Auditing services" },
  { code: "998343", description: "Tax consultancy and preparation services" },
  { code: "998344", description: "Insolvency and receivership services" },
  { code: "998351", description: "Legal advisory and representation services concerning criminal law" },
  { code: "998352", description: "Legal advisory and representation services concerning other fields of law" },
  { code: "998353", description: "Legal documentation and certification services" },
  { code: "998354", description: "Other legal services" },
  { code: "998361", description: "Market research services" },
  { code: "998362", description: "Public opinion polling services" },
  { code: "998371", description: "Veterinary services for pet animals" },
  { code: "998372", description: "Veterinary services for livestock" },
  { code: "998399", description: "Other professional, technical and business services" },
  // Section 13 - Telecommunications and IT Services
  { code: "9984", description: "Telecommunications, broadcasting and information supply services" },
  { code: "998411", description: "Carrier services" },
  { code: "998412", description: "Fixed telephone services" },
  { code: "998413", description: "Mobile telecommunications services" },
  { code: "998414", description: "Private network services" },
  { code: "998415", description: "Data transmission services" },
  { code: "998416", description: "Internet telecommunications services" },
  { code: "998417", description: "Internet backbone services" },
  { code: "998418", description: "Telex services" },
  { code: "998419", description: "Other telecommunications services" },
  { code: "998431", description: "Motion picture, videotape, television programme production services" },
  { code: "998432", description: "Motion picture, videotape, television programme distribution services" },
  { code: "998433", description: "Motion picture projection services" },
  { code: "998434", description: "Radio programme production services" },
  { code: "998435", description: "Radio programme distribution services" },
  { code: "998436", description: "Radio broadcasting services" },
  { code: "998437", description: "Television programme distribution services" },
  { code: "998438", description: "Television broadcasting services" },
  { code: "998439", description: "Other broadcasting services" },
  { code: "998441", description: "On-line information supply services" },
  { code: "998442", description: "Web-search portal services" },
  { code: "998443", description: "Data processing and tabulation services" },
  { code: "998444", description: "Data base services" },
  { code: "998445", description: "News agency services" },
  { code: "998446", description: "Libraries, archives, museums and other cultural services" },
  // Section 14 - Support Services
  { code: "9985", description: "Support services" },
  { code: "998511", description: "Executive/retained personnel search services" },
  { code: "998512", description: "Permanent placement services, other than executive search services" },
  { code: "998513", description: "Contract staffing services" },
  { code: "998514", description: "Temporary staffing services" },
  { code: "998515", description: "Long-term staffing (pay-rolling) services" },
  { code: "998516", description: "Co-employment staffing services" },
  { code: "998519", description: "Other employment and labour supply services" },
  { code: "998521", description: "Investigation services" },
  { code: "998522", description: "Security consulting services" },
  { code: "998523", description: "Armoured car services" },
  { code: "998524", description: "Guard services" },
  { code: "998525", description: "Other security services" },
  { code: "998531", description: "Office administrative services" },
  { code: "998532", description: "Photocopying, document preparation and other specialised office support services" },
  { code: "998533", description: "Convention and trade show organisational services" },
  { code: "998534", description: "Telephone answering and telemarketing services" },
  { code: "998535", description: "Mailing list compilation and mailing services" },
  { code: "998536", description: "Specialised business and management consultancy services" },
  { code: "998537", description: "Maintenance and repair of office and accounting machinery" },
  { code: "998538", description: "Other support services" },
  { code: "998541", description: "Tour operator services" },
  { code: "998542", description: "Travel agency services" },
  { code: "998543", description: "Other reservation services" },
  { code: "998551", description: "Cleaning services of residential buildings, industrial buildings and factories" },
  { code: "998552", description: "Cleaning services of industrial buildings and factories" },
  { code: "998553", description: "Cleaning services of transport equipment" },
  { code: "998554", description: "Furnace and chimney cleaning services" },
  { code: "998555", description: "Exterior cleaning of buildings" },
  { code: "998559", description: "Other cleaning services" },
  { code: "998561", description: "Packaging services" },
  // Section 15 - Education Services
  { code: "9992", description: "Education services" },
  { code: "999210", description: "Pre-primary education services" },
  { code: "999211", description: "Primary education services" },
  { code: "999212", description: "Secondary education services, general" },
  { code: "999213", description: "Secondary education services, technical and vocational" },
  { code: "999214", description: "Higher education services, general" },
  { code: "999215", description: "Higher education services, technical" },
  { code: "999216", description: "Higher education services, vocational" },
  { code: "999217", description: "Higher education services, other" },
  { code: "999218", description: "Higher education services in specialised fields" },
  { code: "999219", description: "Post-school diploma/certificate education services" },
  { code: "999220", description: "Specialty education services" },
  { code: "999240", description: "Cultural education services" },
  { code: "999241", description: "Sports and recreation education services" },
  { code: "999242", description: "Religious instruction/education services" },
  // Section 16 - Healthcare Services
  { code: "9993", description: "Human health and social care services" },
  { code: "999311", description: "Inpatient services" },
  { code: "999312", description: "Medical and dental services" },
  { code: "999313", description: "Childbirth and related services" },
  { code: "999314", description: "Nursing and physiotherapeutic services" },
  { code: "999315", description: "Ambulance services" },
  { code: "999316", description: "Medical laboratory and diagnostic imaging services" },
  { code: "999317", description: "Blood, sperm and organ bank services" },
  { code: "999319", description: "Other human health services including homeopathy, unani, ayurveda, naturopathy, acupuncture etc." },
  { code: "999321", description: "Residential care services for the elderly and persons with disabilities" },
  { code: "999322", description: "Residential care services for children suffering from mental retardation, mental health illnesses or substance abuse" },
  { code: "999323", description: "Residential care services for adults suffering from mental retardation, mental health illnesses or substance abuse" },
  { code: "999324", description: "Other social services with accommodation" },
  // Section 17 - Cultural, Sporting, Amusement and Recreation Services
  { code: "9996", description: "Recreational, cultural and sporting services" },
  { code: "999611", description: "Performing arts event promotion and organisation services" },
  { code: "999612", description: "Performing arts event production and presentation services" },
  { code: "999613", description: "Performing arts facility operation services" },
  { code: "999614", description: "Other performing arts and live entertainment services" },
  { code: "999621", description: "Museum and preservation services of historical sites and buildings" },
  { code: "999622", description: "Botanical garden, zoological garden, nature reserve and national park services" },
  { code: "999631", description: "Amusement park and theme park services" },
  { code: "999632", description: "Gambling and lottery services" },
  { code: "999633", description: "Other amusement and recreation services" },
  { code: "999641", description: "Sports and recreational sports event promotion and organisation services" },
  { code: "999642", description: "Sports event promotion and organisation services" },
  { code: "999643", description: "Sports and recreation facility operation services" },
  { code: "999649", description: "Other sports and recreation services" },
  // Section 18 - IT and Software Services
  { code: "9983", description: "IT and software services" },
  { code: "998313", description: "Information technology (IT) consulting and support services" },
  { code: "998314", description: "Information technology (IT) infrastructure provisioning services" },
  { code: "998315", description: "Information technology (IT) design and development services" },
  { code: "998316", description: "Software design and development services" },
  { code: "998319", description: "Other IT services" },
  // Additional common SAC/HSN codes
  { code: "9954", description: "Works contract services" },
  { code: "9972", description: "Real estate services" },
  { code: "9973", description: "Leasing or rental services" },
  { code: "9974", description: "Water supply, sewage and waste collection, treatment and disposal services" },
  { code: "9975", description: "Postal and courier services" },
  { code: "9976", description: "Electricity, gas, water and other distribution services" },
  { code: "9977", description: "Financial and related services" },
  { code: "9978", description: "Insurance and pension fund services" },
  { code: "9979", description: "Other financial services" },
  { code: "9981", description: "Research and development services" },
  { code: "9982", description: "Legal and accounting services" },
  { code: "9986", description: "Support services to agriculture, hunting, forestry, fishing, mining and utilities" },
  { code: "9987", description: "Maintenance, repair and installation (except construction) services" },
  { code: "9988", description: "Manufacturing services on physical inputs (goods) owned by others" },
  { code: "9989", description: "Other manufacturing services; publishing, printing and reproduction services; materials recovery services" },
  { code: "9991", description: "Public administration and other services provided to the community as a whole; compulsory social security services" },
  { code: "9994", description: "Sewage and waste collection, treatment and disposal and other environmental protection services" },
  { code: "9995", description: "Services of membership organisations" },
  { code: "9997", description: "Other services" },
  { code: "9998", description: "Domestic services" },
  { code: "9999", description: "Services provided by extraterritorial organisations and bodies" },
];
export default hsnData3;
