// HSN Codes - Part 1: Chapters 01–40
const hsnData1 = [
  // Chapter 01 - Live Animals
  { code: "0101", description: "Live horses, asses, mules and hinnies" },
  { code: "0102", description: "Live bovine animals" },
  { code: "0103", description: "Live swine" },
  { code: "0104", description: "Live sheep and goats" },
  { code: "0105", description: "Live poultry (fowls, ducks, geese, turkeys, guinea fowls)" },
  { code: "0106", description: "Other live animals" },
  // Chapter 02 - Meat and edible meat offal
  { code: "0201", description: "Meat of bovine animals, fresh or chilled" },
  { code: "0202", description: "Meat of bovine animals, frozen" },
  { code: "0203", description: "Meat of swine, fresh, chilled or frozen" },
  { code: "0204", description: "Meat of sheep or goats, fresh, chilled or frozen" },
  { code: "0206", description: "Edible offal of bovine animals, swine, sheep, goats" },
  { code: "0207", description: "Meat and edible offal of poultry" },
  { code: "0208", description: "Other meat and edible meat offal, fresh, chilled or frozen" },
  { code: "0209", description: "Pig fat, free of lean meat; poultry fat" },
  { code: "0210", description: "Meat and edible meat offal, salted, in brine, dried or smoked" },
  // Chapter 03 - Fish and crustaceans
  { code: "0301", description: "Live fish" },
  { code: "0302", description: "Fish, fresh or chilled, excluding fish fillets" },
  { code: "0303", description: "Fish, frozen, excluding fish fillets" },
  { code: "0304", description: "Fish fillets and other fish meat" },
  { code: "0305", description: "Fish, dried, salted or in brine; smoked fish" },
  { code: "0306", description: "Crustaceans, whether in shell or not" },
  { code: "0307", description: "Molluscs, whether in shell or not" },
  { code: "0308", description: "Aquatic invertebrates other than crustaceans and molluscs" },
  // Chapter 04 - Dairy produce; eggs; honey
  { code: "0401", description: "Milk and cream, not concentrated nor sweetened" },
  { code: "0402", description: "Milk and cream, concentrated or sweetened" },
  { code: "0403", description: "Buttermilk, curdled milk, cream, yogurt, kephir" },
  { code: "0404", description: "Whey, whether or not concentrated or sweetened" },
  { code: "0405", description: "Butter and other fats and oils derived from milk" },
  { code: "0406", description: "Cheese and curd" },
  { code: "0407", description: "Birds eggs, in shell, fresh, preserved or cooked" },
  { code: "0408", description: "Birds eggs, not in shell, and egg yolks" },
  { code: "0409", description: "Natural honey" },
  { code: "0410", description: "Edible products of animal origin, not elsewhere specified" },
  // Chapter 05 - Products of animal origin
  { code: "0501", description: "Human hair, unworked" },
  { code: "0502", description: "Pigs, hogs or boars bristles and hair; badger hair" },
  { code: "0504", description: "Guts, bladders and stomachs of animals" },
  { code: "0505", description: "Skins and other parts of birds, with their feathers or down" },
  { code: "0506", description: "Bones and horn-cores, unworked" },
  { code: "0507", description: "Ivory, tortoise-shell, whalebone, horns, antlers, hooves" },
  { code: "0508", description: "Coral and similar materials; shells of molluscs" },
  { code: "0510", description: "Ambergris, castoreum, civet and musk; cantharides" },
  { code: "0511", description: "Animal products not elsewhere specified or included" },
  // Chapter 06 - Live trees and other plants
  { code: "0601", description: "Bulbs, tubers, tuberous roots, corms, crowns and rhizomes" },
  { code: "0602", description: "Other live plants (including their roots), cuttings and slips" },
  { code: "0603", description: "Cut flowers and flower buds of a kind suitable for bouquets" },
  { code: "0604", description: "Foliage, branches and other parts of plants, for bouquets" },
  // Chapter 07 - Edible vegetables
  { code: "0701", description: "Potatoes, fresh or chilled" },
  { code: "0702", description: "Tomatoes, fresh or chilled" },
  { code: "0703", description: "Onions, shallots, garlic, leeks and other alliaceous vegetables" },
  { code: "0704", description: "Cabbages, cauliflowers, kohlrabi, kale and similar edible brassicas" },
  { code: "0705", description: "Lettuce and chicory, fresh or chilled" },
  { code: "0706", description: "Carrots, turnips, salad beetroot, salsify, celeriac, radishes" },
  { code: "0707", description: "Cucumbers and gherkins, fresh or chilled" },
  { code: "0708", description: "Leguminous vegetables, shelled or unshelled, fresh or chilled" },
  { code: "0709", description: "Other vegetables, fresh or chilled" },
  { code: "0710", description: "Vegetables (uncooked or cooked), frozen" },
  { code: "0711", description: "Vegetables provisionally preserved, but unsuitable for immediate consumption" },
  { code: "0712", description: "Dried vegetables, whole, cut, sliced, broken or in powder" },
  { code: "0713", description: "Dried leguminous vegetables, shelled" },
  { code: "0714", description: "Manioc, arrowroot, salep, Jerusalem artichokes, sweet potatoes" },
  // Chapter 08 - Edible fruit and nuts
  { code: "0801", description: "Coconuts, Brazil nuts and cashew nuts, fresh or dried" },
  { code: "0802", description: "Other nuts, fresh or dried" },
  { code: "0803", description: "Bananas, including plantains, fresh or dried" },
  { code: "0804", description: "Dates, figs, pineapples, avocados, guavas, mangoes" },
  { code: "0805", description: "Citrus fruit, fresh or dried" },
  { code: "0806", description: "Grapes, fresh or dried" },
  { code: "0807", description: "Melons (including watermelons) and papaws (papayas), fresh" },
  { code: "0808", description: "Apples, pears and quinces, fresh" },
  { code: "0809", description: "Apricots, cherries, peaches, plums and sloes, fresh" },
  { code: "0810", description: "Other fruit, fresh" },
  { code: "0811", description: "Fruit and nuts, uncooked or cooked, frozen" },
  { code: "0813", description: "Fruit, dried, other than that of headings 0801 to 0806" },
  // Chapter 09 - Coffee, tea, spices
  { code: "0901", description: "Coffee, whether or not roasted or decaffeinated" },
  { code: "0902", description: "Tea, whether or not flavoured" },
  { code: "0904", description: "Pepper of the genus Piper; dried or crushed or ground fruits of genus Capsicum" },
  { code: "0905", description: "Vanilla" },
  { code: "0906", description: "Cinnamon and cinnamon-tree flowers" },
  { code: "0907", description: "Cloves (whole fruit, cloves and stems)" },
  { code: "0908", description: "Nutmeg, mace and cardamoms" },
  { code: "0909", description: "Seeds of anise, badian, fennel, coriander, cumin or caraway" },
  { code: "0910", description: "Ginger, saffron, turmeric (curcuma), thyme, bay leaves, curry" },
  // Chapter 10 - Cereals
  { code: "1001", description: "Wheat and meslin" },
  { code: "1002", description: "Rye" },
  { code: "1003", description: "Barley" },
  { code: "1004", description: "Oats" },
  { code: "1005", description: "Maize (corn)" },
  { code: "1006", description: "Rice" },
  { code: "1007", description: "Grain sorghum" },
  { code: "1008", description: "Buckwheat, millet and canary seed; other cereals" },
  // Chapter 11 - Milling industry products
  { code: "1101", description: "Wheat or meslin flour" },
  { code: "1102", description: "Cereal flours other than of wheat or meslin" },
  { code: "1103", description: "Cereal groats, meal and pellets" },
  { code: "1104", description: "Cereal grains otherwise worked (hulled, rolled, flaked, etc.)" },
  { code: "1105", description: "Flour, meal, powder, flakes, granules and pellets of potatoes" },
  { code: "1106", description: "Flour, meal and powder of dried leguminous vegetables" },
  { code: "1107", description: "Malt, whether or not roasted" },
  { code: "1108", description: "Starches; inulin" },
  // Chapter 12 - Oil seeds and oleaginous fruits
  { code: "1201", description: "Soya beans, whether or not broken" },
  { code: "1202", description: "Ground-nuts, not roasted or otherwise cooked" },
  { code: "1203", description: "Copra" },
  { code: "1204", description: "Linseed, whether or not broken" },
  { code: "1205", description: "Rape or colza seeds, whether or not broken" },
  { code: "1206", description: "Sunflower seeds, whether or not broken" },
  { code: "1207", description: "Other oil seeds and oleaginous fruits" },
  { code: "1208", description: "Flours and meals of oil seeds or oleaginous fruits" },
  { code: "1209", description: "Seeds, fruit and spores, of a kind used for sowing" },
  { code: "1210", description: "Hop cones, fresh or dried" },
  { code: "1211", description: "Plants and parts of plants used in perfumery, pharmacy" },
  { code: "1212", description: "Locust beans, seaweeds and other algae, sugar beet and sugar cane" },
  { code: "1213", description: "Cereal straw and husks, unprepared" },
  // Chapter 13 - Lac; gums, resins
  { code: "1301", description: "Lac; natural gums, resins, gum-resins and oleoresins" },
  { code: "1302", description: "Vegetable saps and extracts; pectic substances" },
  // Chapter 15 - Animal or vegetable fats and oils
  { code: "1501", description: "Pig fat (including lard) and poultry fat" },
  { code: "1502", description: "Fats of bovine animals, sheep or goats" },
  { code: "1503", description: "Lard stearin, lard oil, oleostearin, oleo-oil and tallow oil" },
  { code: "1504", description: "Fats and oils and their fractions, of fish or marine mammals" },
  { code: "1505", description: "Wool grease and fatty substances derived therefrom" },
  { code: "1507", description: "Soya-bean oil and its fractions" },
  { code: "1508", description: "Ground-nut oil and its fractions" },
  { code: "1509", description: "Olive oil and its fractions" },
  { code: "1511", description: "Palm oil and its fractions" },
  { code: "1512", description: "Sunflower-seed, safflower or cotton-seed oil and fractions" },
  { code: "1513", description: "Coconut (copra), palm kernel or babassu oil and fractions" },
  { code: "1514", description: "Rape, colza or mustard oil and fractions" },
  { code: "1515", description: "Other fixed vegetable fats and oils and their fractions" },
  { code: "1516", description: "Animal or vegetable fats and oils, hydrogenated" },
  { code: "1517", description: "Margarine; edible mixtures or preparations of animal or vegetable fats" },
  { code: "1518", description: "Animal or vegetable fats and oils, boiled, oxidised, dehydrated" },
  { code: "1520", description: "Glycerol, crude; glycerol waters and glycerol lyes" },
  { code: "1521", description: "Vegetable waxes, beeswax, other insect waxes and spermaceti" },
  { code: "1522", description: "Degras; residues resulting from treatment of fatty substances" },
  // Chapter 16 - Preparations of meat, fish
  { code: "1601", description: "Sausages and similar products, of meat, offal or blood" },
  { code: "1602", description: "Other prepared or preserved meat, offal or blood" },
  { code: "1603", description: "Extracts and juices of meat, fish or crustaceans" },
  { code: "1604", description: "Prepared or preserved fish; caviar and caviar substitutes" },
  { code: "1605", description: "Crustaceans, molluscs and other aquatic invertebrates, prepared" },
  // Chapter 17 - Sugars and sugar confectionery
  { code: "1701", description: "Cane or beet sugar and chemically pure sucrose, in solid form" },
  { code: "1702", description: "Other sugars, including lactose, maltose, glucose and fructose" },
  { code: "1703", description: "Molasses resulting from the extraction or refining of sugar" },
  { code: "1704", description: "Sugar confectionery (including white chocolate), not containing cocoa" },
  // Chapter 18 - Cocoa and cocoa preparations
  { code: "1801", description: "Cocoa beans, whole or broken, raw or roasted" },
  { code: "1802", description: "Cocoa shells, husks, skins and other cocoa waste" },
  { code: "1803", description: "Cocoa paste, whether or not defatted" },
  { code: "1804", description: "Cocoa butter, fat and oil" },
  { code: "1805", description: "Cocoa powder, not containing added sugar or sweetening matter" },
  { code: "1806", description: "Chocolate and other food preparations containing cocoa" },
  // Chapter 19 - Preparations of cereals, flour, starch
  { code: "1901", description: "Malt extract; food preparations of flour, groats, meal, starch" },
  { code: "1902", description: "Pasta, whether or not cooked or stuffed (spaghetti, macaroni, noodles)" },
  { code: "1903", description: "Tapioca and substitutes therefor prepared from starch" },
  { code: "1904", description: "Prepared foods obtained by swelling or roasting of cereals (cornflakes)" },
  { code: "1905", description: "Bread, pastry, cakes, biscuits and other bakers wares" },
  // Chapter 20 - Preparations of vegetables, fruit, nuts
  { code: "2001", description: "Vegetables, fruit, nuts, etc. prepared or preserved by vinegar" },
  { code: "2002", description: "Tomatoes prepared or preserved other than by vinegar" },
  { code: "2003", description: "Mushrooms and truffles, prepared or preserved" },
  { code: "2004", description: "Other vegetables prepared or preserved, frozen" },
  { code: "2005", description: "Other vegetables prepared or preserved, not frozen" },
  { code: "2006", description: "Vegetables, fruit, nuts, fruit-peel, candied with sugar" },
  { code: "2007", description: "Jams, fruit jellies, marmalades, fruit or nut puree" },
  { code: "2008", description: "Fruit, nuts and other edible parts of plants, otherwise prepared" },
  { code: "2009", description: "Fruit juices (including grape must) and vegetable juices" },
  // Chapter 21 - Miscellaneous edible preparations
  { code: "2101", description: "Extracts, essences and concentrates of coffee, tea or mate" },
  { code: "2102", description: "Yeasts (active or inactive); other single-cell micro-organisms" },
  { code: "2103", description: "Sauces and preparations therefor; mixed condiments and mixed seasonings" },
  { code: "2104", description: "Soups and broths and preparations therefor; homogenised composite food preparations" },
  { code: "2105", description: "Ice cream and other edible ice, whether or not containing cocoa" },
  { code: "2106", description: "Food preparations not elsewhere specified or included" },
  // Chapter 22 - Beverages, spirits and vinegar
  { code: "2201", description: "Waters, including natural or artificial mineral waters and aerated waters" },
  { code: "2202", description: "Waters, including mineral waters and aerated waters, containing added sugar" },
  { code: "2203", description: "Beer made from malt" },
  { code: "2204", description: "Wine of fresh grapes, including fortified wines" },
  { code: "2205", description: "Vermouth and other wine of fresh grapes flavoured with plants or aromatic substances" },
  { code: "2206", description: "Other fermented beverages (cider, perry, mead)" },
  { code: "2207", description: "Undenatured ethyl alcohol of an alcoholic strength by volume of >= 80%" },
  { code: "2208", description: "Undenatured ethyl alcohol of an alcoholic strength by volume of < 80%" },
  { code: "2209", description: "Vinegar and substitutes for vinegar obtained from acetic acid" },
  // Chapter 23 - Residues from food industries; prepared animal fodder
  { code: "2301", description: "Flours, meals and pellets, of meat or meat offal, of fish" },
  { code: "2302", description: "Bran, sharps and other residues of cereals or leguminous plants" },
  { code: "2303", description: "Residues of starch manufacture and similar residues" },
  { code: "2304", description: "Oil-cake and other solid residues, of soya-bean oil extraction" },
  { code: "2305", description: "Oil-cake and other solid residues of ground-nut oil extraction" },
  { code: "2306", description: "Oil-cake and other solid residues of vegetable fats or oils" },
  { code: "2307", description: "Wine lees; argol" },
  { code: "2308", description: "Vegetable materials and vegetable waste, used in animal feeding" },
  { code: "2309", description: "Preparations of a kind used in animal feeding" },
  // Chapter 24 - Tobacco
  { code: "2401", description: "Unmanufactured tobacco; tobacco refuse" },
  { code: "2402", description: "Cigars, cheroots, cigarillos and cigarettes, of tobacco or substitutes" },
  { code: "2403", description: "Other manufactured tobacco and manufactured tobacco substitutes" },
  // Chapter 25 - Salt; sulphur; earths and stone
  { code: "2501", description: "Salt (including table salt and denatured salt) and pure sodium chloride" },
  { code: "2502", description: "Unroasted iron pyrites" },
  { code: "2503", description: "Sulphur of all kinds, other than sublimed sulphur, precipitated sulphur and colloidal sulphur" },
  { code: "2504", description: "Natural graphite" },
  { code: "2505", description: "Natural sands of all kinds, whether or not coloured" },
  { code: "2506", description: "Quartz; quartzite, whether or not roughly trimmed or merely cut" },
  { code: "2507", description: "Kaolin and other kaolinic clays, whether or not calcined" },
  { code: "2508", description: "Other clays, andalusite, kyanite and sillimanite" },
  { code: "2509", description: "Chalk" },
  { code: "2510", description: "Natural calcium phosphates, natural aluminium calcium phosphates" },
  { code: "2511", description: "Natural barium sulphate (barytes); natural barium carbonate (witherite)" },
  { code: "2512", description: "Siliceous fossil meals and similar siliceous earths" },
  { code: "2513", description: "Pumice stone; emery; natural corundum, natural garnet and other natural abrasives" },
  { code: "2514", description: "Slate, whether or not roughly trimmed or merely cut" },
  { code: "2515", description: "Marble, travertine, ecaussine and other calcareous monumental or building stone" },
  { code: "2516", description: "Granite, porphyry, basalt, sandstone and other monumental or building stone" },
  { code: "2517", description: "Pebbles, gravel, broken or crushed stone" },
  { code: "2518", description: "Dolomite, whether or not calcined or sintered" },
  { code: "2519", description: "Natural magnesium carbonate (magnesite)" },
  { code: "2520", description: "Gypsum; anhydrite; plasters" },
  { code: "2521", description: "Limestone flux; limestone and other calcareous stone" },
  { code: "2522", description: "Quicklime, slaked lime and hydraulic lime" },
  { code: "2523", description: "Portland cement, aluminous cement, slag cement, supersulphate cement" },
  { code: "2524", description: "Asbestos" },
  { code: "2525", description: "Mica, including splittings and waste" },
  { code: "2526", description: "Natural steatite (talc), whether or not roughly trimmed or cut" },
  { code: "2528", description: "Natural borates and concentrates thereof" },
  { code: "2529", description: "Feldspar; leucite; nepheline and nepheline syenite; fluorspar" },
  { code: "2530", description: "Mineral substances not elsewhere specified or included" },
  // Chapter 26 - Ores, slag and ash
  { code: "2601", description: "Iron ores and concentrates, including roasted iron pyrites" },
  { code: "2602", description: "Manganese ores and concentrates" },
  { code: "2603", description: "Copper ores and concentrates" },
  { code: "2604", description: "Nickel ores and concentrates" },
  { code: "2605", description: "Cobalt ores and concentrates" },
  { code: "2606", description: "Aluminium ores and concentrates" },
  { code: "2607", description: "Lead ores and concentrates" },
  { code: "2608", description: "Zinc ores and concentrates" },
  { code: "2609", description: "Tin ores and concentrates" },
  { code: "2610", description: "Chromium ores and concentrates" },
  { code: "2611", description: "Tungsten ores and concentrates" },
  { code: "2612", description: "Uranium or thorium ores and concentrates" },
  { code: "2613", description: "Molybdenum ores and concentrates" },
  { code: "2614", description: "Titanium ores and concentrates" },
  { code: "2615", description: "Niobium, tantalum, vanadium or zirconium ores and concentrates" },
  { code: "2616", description: "Precious metal ores and concentrates" },
  { code: "2617", description: "Other ores and concentrates" },
  { code: "2618", description: "Granulated slag (slag sand) from manufacture of iron or steel" },
  { code: "2619", description: "Slag, dross, scalings and other waste from iron/steel manufacture" },
  { code: "2620", description: "Slag, ash and residues (other than from the manufacture of iron or steel)" },
  // Chapter 27 - Mineral fuels, oils
  { code: "2701", description: "Coal; briquettes, ovoids and similar solid fuels manufactured from coal" },
  { code: "2702", description: "Lignite, whether or not agglomerated, excluding jet" },
  { code: "2703", description: "Peat (including peat litter), whether or not agglomerated" },
  { code: "2704", description: "Coke and semi-coke of coal, of lignite or of peat" },
  { code: "2705", description: "Coal gas, water gas, producer gas and similar gases" },
  { code: "2706", description: "Tar distilled from coal, from lignite or from peat" },
  { code: "2707", description: "Oils and other products of the distillation of high temperature coal tar" },
  { code: "2708", description: "Pitch and pitch coke, obtained from coal tar or from other mineral tars" },
  { code: "2709", description: "Petroleum oils and oils obtained from bituminous minerals, crude" },
  { code: "2710", description: "Petroleum oils and oils obtained from bituminous minerals, not crude" },
  { code: "2711", description: "Petroleum gases and other gaseous hydrocarbons (LPG, natural gas)" },
  { code: "2712", description: "Petroleum jelly; paraffin wax, other petroleum waxes" },
  { code: "2713", description: "Petroleum coke, petroleum bitumen and other residues" },
  { code: "2714", description: "Bitumen and asphalt, natural; bituminous or oil shale and tar sands" },
  { code: "2715", description: "Bituminous mixtures based on natural asphalt" },
  { code: "2716", description: "Electrical energy" },
  // Chapter 28 - Inorganic chemicals
  { code: "2801", description: "Fluorine, chlorine, bromine and iodine" },
  { code: "2802", description: "Sulphur, sublimed or precipitated; colloidal sulphur" },
  { code: "2803", description: "Carbon (carbon blacks and other forms of carbon)" },
  { code: "2804", description: "Hydrogen, rare gases and other non-metals" },
  { code: "2805", description: "Alkali or alkaline-earth metals; rare-earth metals" },
  { code: "2806", description: "Hydrogen chloride (hydrochloric acid); chlorosulphuric acid" },
  { code: "2807", description: "Sulphuric acid; oleum" },
  { code: "2808", description: "Nitric acid; sulphonitric acids" },
  { code: "2809", description: "Diphosphorus pentaoxide; phosphoric acid; polyphosphoric acids" },
  { code: "2810", description: "Oxides of boron; boric acids" },
  { code: "2811", description: "Other inorganic acids and other inorganic oxygen compounds of non-metals" },
  { code: "2812", description: "Halides and halide oxides of non-metals" },
  { code: "2813", description: "Sulphides of non-metals; commercial phosphorus trisulphide" },
  { code: "2814", description: "Ammonia, anhydrous or in aqueous solution" },
  { code: "2815", description: "Sodium hydroxide (caustic soda); potassium hydroxide (caustic potash)" },
  { code: "2816", description: "Hydroxide and peroxide of magnesium; oxides, hydroxides and peroxides of strontium or barium" },
  { code: "2817", description: "Zinc oxide; zinc peroxide" },
  { code: "2818", description: "Artificial corundum; aluminium oxide; aluminium hydroxide" },
  { code: "2819", description: "Chromium oxides and hydroxides" },
  { code: "2820", description: "Manganese oxides" },
  { code: "2821", description: "Iron oxides and hydroxides; earth colours" },
  { code: "2822", description: "Cobalt oxides and hydroxides; commercial cobalt oxides" },
  { code: "2823", description: "Titanium oxides" },
  { code: "2824", description: "Lead oxides; red lead and orange lead" },
  { code: "2825", description: "Hydrazine and hydroxylamine and their inorganic salts" },
  { code: "2826", description: "Fluorides; fluorosilicates, fluoroaluminates and other complex fluorine salts" },
  { code: "2827", description: "Chlorides, chloride oxides and chloride hydroxides" },
  { code: "2828", description: "Hypochlorites; commercial calcium hypochlorite; chlorites; hypobromites" },
  { code: "2829", description: "Chlorates and perchlorates; bromates and perbromates; iodates and periodates" },
  { code: "2830", description: "Sulphides; polysulphides" },
  { code: "2831", description: "Dithionites and sulphoxylates" },
  { code: "2832", description: "Sulphites; thiosulphates" },
  { code: "2833", description: "Sulphates; alums; peroxosulphates (persulphates)" },
  { code: "2834", description: "Nitrites; nitrates" },
  { code: "2835", description: "Phosphinates, phosphonates, phosphates and polyphosphates" },
  { code: "2836", description: "Carbonates; peroxocarbonates; commercial ammonium carbonate" },
  { code: "2837", description: "Cyanides, cyanide oxides and complex cyanides" },
  { code: "2839", description: "Silicates; commercial alkali metal silicates" },
  { code: "2840", description: "Borates; peroxoborates (perborates)" },
  { code: "2841", description: "Salts of oxometallic or peroxometallic acids" },
  { code: "2842", description: "Other salts of inorganic acids or peroxoacids" },
  { code: "2843", description: "Colloidal precious metals; compounds of precious metals" },
  { code: "2844", description: "Radioactive chemical elements and radioactive isotopes" },
  { code: "2845", description: "Isotopes other than those of heading 2844" },
  { code: "2846", description: "Compounds, inorganic or organic, of rare-earth metals" },
  { code: "2847", description: "Hydrogen peroxide" },
  { code: "2848", description: "Phosphides" },
  { code: "2849", description: "Carbides" },
  { code: "2850", description: "Hydrides, nitrides, azides, silicides and borides" },
  { code: "2852", description: "Mercury compounds" },
  { code: "2853", description: "Other inorganic compounds" },
  // Chapter 29 - Organic chemicals
  { code: "2901", description: "Acyclic hydrocarbons" },
  { code: "2902", description: "Cyclic hydrocarbons" },
  { code: "2903", description: "Halogenated derivatives of hydrocarbons" },
  { code: "2904", description: "Sulphonated, nitrated or nitrosated derivatives of hydrocarbons" },
  { code: "2905", description: "Acyclic alcohols and their halogenated, sulphonated, nitrated or nitrosated derivatives" },
  { code: "2906", description: "Cyclic alcohols and their halogenated, sulphonated, nitrated or nitrosated derivatives" },
  { code: "2907", description: "Phenols; phenol-alcohols" },
  { code: "2908", description: "Halogenated, sulphonated, nitrated or nitrosated derivatives of phenols" },
  { code: "2909", description: "Ethers, ether-alcohols, ether-phenols, ether-alcohol-phenols, alcohol peroxides" },
  { code: "2910", description: "Epoxides, epoxyalcohols, epoxyphenols and epoxyethers" },
  { code: "2911", description: "Acetals and hemiacetals, with or without other oxygen function" },
  { code: "2912", description: "Aldehydes, whether or not with other oxygen function" },
  { code: "2913", description: "Halogenated, sulphonated, nitrated or nitrosated derivatives of aldehyde-function compounds" },
  { code: "2914", description: "Ketones and quinones, whether or not with other oxygen function" },
  { code: "2915", description: "Saturated acyclic monocarboxylic acids and their anhydrides, halides, peroxides" },
  { code: "2916", description: "Unsaturated acyclic monocarboxylic acids, cyclic monocarboxylic acids" },
  { code: "2917", description: "Polycarboxylic acids, their anhydrides, halides, peroxides and peroxyacids" },
  { code: "2918", description: "Carboxylic acids with additional oxygen function" },
  { code: "2919", description: "Phosphoric esters and their salts" },
  { code: "2920", description: "Esters of other inorganic acids of non-metals and their salts" },
  { code: "2921", description: "Amine-function compounds" },
  { code: "2922", description: "Oxygen-function amino-compounds" },
  { code: "2923", description: "Quaternary ammonium salts and hydroxides; lecithins and other phosphoaminolipids" },
  { code: "2924", description: "Carboxyamide-function compounds; amide-function compounds of carbonic acid" },
  { code: "2925", description: "Carboxyimide-function compounds (including saccharin and its salts) and imine-function compounds" },
  { code: "2926", description: "Nitrile-function compounds" },
  { code: "2927", description: "Diazo-, azo- or azoxy-compounds" },
  { code: "2928", description: "Organic derivatives of hydrazine or of hydroxylamine" },
  { code: "2929", description: "Compounds with other nitrogen function" },
  { code: "2930", description: "Organo-sulphur compounds" },
  { code: "2931", description: "Other organo-inorganic compounds" },
  { code: "2932", description: "Heterocyclic compounds with oxygen hetero-atom(s) only" },
  { code: "2933", description: "Heterocyclic compounds with nitrogen hetero-atom(s) only" },
  { code: "2934", description: "Nucleic acids and their salts; other heterocyclic compounds" },
  { code: "2935", description: "Sulphonamides" },
  { code: "2936", description: "Provitamins and vitamins, natural or reproduced by synthesis" },
  { code: "2937", description: "Hormones, prostaglandins, thromboxanes and leukotrienes" },
  { code: "2938", description: "Glycosides, natural or reproduced by synthesis" },
  { code: "2939", description: "Alkaloids, natural or reproduced by synthesis, and their salts" },
  { code: "2940", description: "Sugars, chemically pure, other than sucrose, lactose, maltose, glucose" },
  { code: "2941", description: "Antibiotics" },
  { code: "2942", description: "Other organic compounds" },
  // Chapter 30 - Pharmaceutical products
  { code: "3001", description: "Glands and other organs for organo-therapeutic uses" },
  { code: "3002", description: "Human blood; animal blood prepared for therapeutic, prophylactic or diagnostic uses" },
  { code: "3003", description: "Medicaments (not in measured doses or in forms/packings for retail sale)" },
  { code: "3004", description: "Medicaments consisting of mixed or unmixed products for therapeutic or prophylactic uses, put up in measured doses for retail sale" },
  { code: "3005", description: "Wadding, gauze, bandages and similar articles dipped or coated with pharmaceutical substances" },
  { code: "3006", description: "Pharmaceutical goods specified in Note 4 to this Chapter" },
  // Chapter 31 - Fertilisers
  { code: "3101", description: "Animal or vegetable fertilisers" },
  { code: "3102", description: "Mineral or chemical fertilisers, nitrogenous" },
  { code: "3103", description: "Mineral or chemical fertilisers, phosphatic" },
  { code: "3104", description: "Mineral or chemical fertilisers, potassic" },
  { code: "3105", description: "Mineral or chemical fertilisers containing two or three of the fertilising elements" },
  // Chapter 32 - Tanning or dyeing extracts; dyes, pigments
  { code: "3201", description: "Tanning extracts of vegetable origin; tannins and their salts, ethers, esters and other derivatives" },
  { code: "3202", description: "Synthetic organic tanning substances; inorganic tanning substances" },
  { code: "3203", description: "Colouring matter of vegetable or animal origin" },
  { code: "3204", description: "Synthetic organic colouring matter; preparations based on synthetic organic colouring matter" },
  { code: "3205", description: "Colour lakes; preparations based on colour lakes" },
  { code: "3206", description: "Other colouring matter; preparations as specified in Note 3 to this Chapter" },
  { code: "3207", description: "Prepared pigments, prepared opacifiers and prepared colours, vitrifiable enamels and glazes, engobes, liquid lustres" },
  { code: "3208", description: "Paints and varnishes based on synthetic polymers or chemically modified natural polymers" },
  { code: "3209", description: "Paints and varnishes based on acrylic or vinyl polymers, in aqueous medium" },
  { code: "3210", description: "Other paints and varnishes; prepared water pigments for finishing leather" },
  { code: "3211", description: "Prepared driers" },
  { code: "3212", description: "Pigments (including metallic powders and flakes) dispersed in non-aqueous media" },
  { code: "3213", description: "Artists, students or signboard painters colours, modifying tints, amusement colours" },
  { code: "3214", description: "Glaziers putty, grafting putty, resin cements, caulking compounds and other mastics" },
  { code: "3215", description: "Printing ink, writing or drawing ink and other inks" },
  // Chapter 33 - Essential oils and resinoids; perfumery, cosmetic preparations
  { code: "3301", description: "Essential oils, whether or not terpeneless; resinoids; extracted oleoresins" },
  { code: "3302", description: "Mixtures of odoriferous substances and mixtures (including alcoholic solutions)" },
  { code: "3303", description: "Perfumes and toilet waters" },
  { code: "3304", description: "Beauty or make-up preparations and preparations for the care of the skin" },
  { code: "3305", description: "Preparations for use on the hair (shampoos, hair spray, hair colour)" },
  { code: "3306", description: "Preparations for oral or dental hygiene, including denture fixative pastes and powders" },
  { code: "3307", description: "Pre-shave, shaving or after-shave preparations, personal deodorants, bath preparations" },
  // Chapter 34 - Soap, organic surface-active agents, washing preparations
  { code: "3401", description: "Soap; organic surface-active products and preparations for use as soap, in the form of bars, cakes, moulded pieces or shapes" },
  { code: "3402", description: "Organic surface-active agents (other than soap); surface-active preparations, washing preparations, cleaning preparations" },
  { code: "3403", description: "Lubricating preparations (including cutting-oil preparations, bolt or nut release preparations)" },
  { code: "3404", description: "Artificial waxes and prepared waxes" },
  { code: "3405", description: "Polishes and creams, for footwear, furniture, floors, bodywork, glass or metal" },
  { code: "3406", description: "Candles, tapers and the like" },
  { code: "3407", description: "Modelling pastes, including those put up for childrens amusement" },
  // Chapter 35 - Albuminoidal substances; modified starches; glues; enzymes
  { code: "3501", description: "Casein, caseinates and other casein derivatives; casein glues" },
  { code: "3502", description: "Albumins, albuminates and other albumin derivatives" },
  { code: "3503", description: "Gelatin (including gelatin in rectangular sheets, surface-worked or coloured) and gelatin derivatives" },
  { code: "3504", description: "Peptones and their derivatives; other protein substances" },
  { code: "3505", description: "Dextrins and other modified starches; glues based on starches, on dextrins or on other modified starches" },
  { code: "3506", description: "Prepared glues and other prepared adhesives" },
  { code: "3507", description: "Enzymes; prepared enzymes not elsewhere specified or included" },
  // Chapter 36 - Explosives; pyrotechnic products; matches
  { code: "3601", description: "Propellent powders" },
  { code: "3602", description: "Prepared explosives, other than propellent powders" },
  { code: "3603", description: "Safety fuses; detonating fuses; percussion or detonating caps; igniters; electric detonators" },
  { code: "3604", description: "Fireworks, signalling flares, rain rockets, fog signals and other pyrotechnic articles" },
  { code: "3605", description: "Matches, other than pyrotechnic articles of heading 3604" },
  { code: "3606", description: "Ferro-cerium and other pyrophoric alloys in all forms; articles of combustible materials" },
  // Chapter 37 - Photographic or cinematographic goods
  { code: "3701", description: "Photographic plates and film in the flat, sensitised, unexposed" },
  { code: "3702", description: "Photographic film in rolls, sensitised, unexposed" },
  { code: "3703", description: "Photographic paper, paperboard and textiles, sensitised, unexposed" },
  { code: "3704", description: "Photographic plates, film, paper, paperboard and textiles, exposed but not developed" },
  { code: "3705", description: "Photographic plates and film, exposed and developed, other than cinematographic film" },
  { code: "3706", description: "Cinematographic film, exposed and developed, whether or not incorporating sound track" },
  { code: "3707", description: "Chemical preparations for photographic uses" },
  // Chapter 38 - Miscellaneous chemical products
  { code: "3801", description: "Artificial graphite; colloidal or semi-colloidal graphite; preparations based on graphite or other carbon" },
  { code: "3802", description: "Activated carbon; activated natural mineral products; animal black" },
  { code: "3803", description: "Tall oil, whether or not refined" },
  { code: "3804", description: "Residual lyes from the manufacture of wood pulp, whether or not concentrated" },
  { code: "3805", description: "Gum, wood or sulphate turpentine and other terpenic oils" },
  { code: "3806", description: "Rosin and resin acids, and derivatives thereof" },
  { code: "3807", description: "Wood tar; wood tar oils; wood creosote; wood naphtha; vegetable pitch" },
  { code: "3808", description: "Insecticides, rodenticides, fungicides, herbicides, anti-sprouting products and plant-growth regulators" },
  { code: "3809", description: "Finishing agents, dye carriers to accelerate the dyeing or fixing of dyestuffs" },
  { code: "3810", description: "Pickling preparations for metal surfaces; fluxes and other auxiliary preparations for soldering" },
  { code: "3811", description: "Anti-knock preparations, oxidation inhibitors, gum inhibitors, viscosity improvers, anti-corrosive preparations for mineral oils" },
  { code: "3812", description: "Prepared rubber accelerators; compound plasticisers for rubber or plastics" },
  { code: "3813", description: "Preparations and charges for fire-extinguishers; charged fire-extinguishing grenades" },
  { code: "3814", description: "Organic composite solvents and thinners; prepared paint or varnish removers" },
  { code: "3815", description: "Reaction initiators, reaction accelerators and catalytic preparations" },
  { code: "3816", description: "Refractory cements, mortars, concretes and similar compositions" },
  { code: "3817", description: "Mixed alkylbenzenes and mixed alkylnaphthalenes" },
  { code: "3818", description: "Chemical elements doped for use in electronics, in the form of discs, wafers or similar forms" },
  { code: "3819", description: "Hydraulic brake fluids and other prepared liquids for hydraulic transmission" },
  { code: "3820", description: "Anti-freezing preparations and prepared de-icing fluids" },
  { code: "3821", description: "Prepared culture media for the development or maintenance of micro-organisms" },
  { code: "3822", description: "Diagnostic or laboratory reagents on a backing and prepared diagnostic or laboratory reagents" },
  { code: "3823", description: "Industrial monocarboxylic fatty acids; acid oils from refining; industrial fatty alcohols" },
  { code: "3824", description: "Prepared binders for foundry moulds or cores; chemical products and preparations of the chemical or allied industries" },
  { code: "3825", description: "Residual products of the chemical or allied industries, not elsewhere specified or included" },
  { code: "3826", description: "Biodiesel and mixtures thereof, not containing or containing less than 70% by weight of petroleum oils" },
  // Chapter 39 - Plastics and articles thereof
  { code: "3901", description: "Polymers of ethylene, in primary forms" },
  { code: "3902", description: "Polymers of propylene or of other olefins, in primary forms" },
  { code: "3903", description: "Polymers of styrene, in primary forms" },
  { code: "3904", description: "Polymers of vinyl chloride or of other halogenated olefins, in primary forms" },
  { code: "3905", description: "Polymers of vinyl acetate or of other vinyl esters, in primary forms" },
  { code: "3906", description: "Acrylic polymers in primary forms" },
  { code: "3907", description: "Polyacetals, other polyethers and epoxide resins, in primary forms; polycarbonates, alkyd resins" },
  { code: "3908", description: "Polyamides in primary forms" },
  { code: "3909", description: "Amino-resins, phenolic resins and polyurethanes, in primary forms" },
  { code: "3910", description: "Silicones in primary forms" },
  { code: "3911", description: "Petroleum resins, coumarone-indene resins, polyterpenes, polysulphides, polysulphones" },
  { code: "3912", description: "Cellulose and its chemical derivatives, not elsewhere specified or included, in primary forms" },
  { code: "3913", description: "Natural polymers and modified natural polymers, not elsewhere specified or included, in primary forms" },
  { code: "3914", description: "Ion-exchangers based on polymers of headings 3901 to 3913, in primary forms" },
  { code: "3915", description: "Waste, parings and scrap, of plastics" },
  { code: "3916", description: "Monofilament of which any cross-sectional dimension exceeds 1 mm, rods, sticks and profile shapes, of plastics" },
  { code: "3917", description: "Tubes, pipes and hoses, and fittings therefor, of plastics" },
  { code: "3918", description: "Floor coverings of plastics, whether or not self-adhesive, in rolls or in the form of tiles" },
  { code: "3919", description: "Self-adhesive plates, sheets, film, foil, tape, strip and other flat shapes, of plastics" },
  { code: "3920", description: "Other plates, sheets, film, foil and strip, of plastics, non-cellular and not reinforced, laminated, supported or similarly combined with other materials" },
  { code: "3921", description: "Other plates, sheets, film, foil and strip, of plastics" },
  { code: "3922", description: "Baths, shower-baths, sinks, wash-basins, bidets, lavatory pans, seats and covers, flushing cisterns and similar sanitary ware, of plastics" },
  { code: "3923", description: "Articles for the conveyance or packing of goods, of plastics; stoppers, lids, caps and other closures, of plastics" },
  { code: "3924", description: "Tableware, kitchenware, other household articles and hygienic or toilet articles, of plastics" },
  { code: "3925", description: "Builders ware of plastics, not elsewhere specified or included" },
  { code: "3926", description: "Other articles of plastics and articles of other materials of headings 3901 to 3914" },
  // Chapter 40 - Rubber and articles thereof
  { code: "4001", description: "Natural rubber, balata, gutta-percha, guayule, chicle and similar natural gums, in primary forms or in plates, sheets or strip" },
  { code: "4002", description: "Synthetic rubber and factice derived from oils, in primary forms or in plates, sheets or strip" },
  { code: "4003", description: "Reclaimed rubber in primary forms or in plates, sheets or strip" },
  { code: "4004", description: "Waste, parings and scrap of rubber (other than hard rubber) and powders and granules obtained therefrom" },
  { code: "4005", description: "Compounded rubber, unvulcanised, in primary forms or in plates, sheets or strip" },
  { code: "4006", description: "Other forms (rods, tubes, profiles, etc.) and articles of unvulcanised rubber" },
  { code: "4007", description: "Vulcanised rubber thread and cord" },
  { code: "4008", description: "Plates, sheets, strip, rods and profile shapes, of vulcanised rubber other than hard rubber" },
  { code: "4009", description: "Tubes, pipes and hoses, of vulcanised rubber other than hard rubber" },
  { code: "4010", description: "Conveyor or transmission belts or belting, of vulcanised rubber" },
  { code: "4011", description: "New pneumatic tyres, of rubber" },
  { code: "4012", description: "Retreaded or used pneumatic tyres of rubber; solid or cushion tyres, tyre treads and tyre flaps" },
  { code: "4013", description: "Inner tubes, of rubber" },
  { code: "4014", description: "Hygienic or pharmaceutical articles (including teats), of vulcanised rubber other than hard rubber" },
  { code: "4015", description: "Articles of apparel and clothing accessories (including gloves, mittens and mitts), for all purposes, of vulcanised rubber" },
  { code: "4016", description: "Other articles of vulcanised rubber other than hard rubber" },
  { code: "4017", description: "Hard rubber (for example, ebonite) in all forms, including waste and scrap; articles of hard rubber" },
];
export default hsnData1;
