// HSN Codes - Part 2: Chapters 41–84
const hsnData2 = [
  // Chapter 41 - Raw hides and skins (other than furskins) and leather
  { code: "4101", description: "Raw hides and skins of bovine or equine animals, fresh or preserved" },
  { code: "4102", description: "Raw skins of sheep or lambs, fresh or preserved" },
  { code: "4103", description: "Other raw hides and skins, fresh or preserved" },
  { code: "4104", description: "Tanned or crust hides and skins of bovine or equine animals, without hair on" },
  { code: "4105", description: "Tanned or crust skins of sheep or lambs, without wool on" },
  { code: "4106", description: "Tanned or crust hides and skins of other animals, without wool or hair on" },
  { code: "4107", description: "Leather further prepared after tanning or crusting, including parchment-dressed leather, of bovine or equine animals" },
  { code: "4112", description: "Leather further prepared after tanning or crusting, of sheep or lamb" },
  { code: "4113", description: "Leather further prepared after tanning or crusting, of other animals" },
  { code: "4114", description: "Chamois (including combination chamois) leather; patent leather and patent laminated leather; metallised leather" },
  { code: "4115", description: "Composition leather with a basis of leather or leather fibre" },
  // Chapter 42 - Articles of leather; saddlery and harness; travel goods, handbags
  { code: "4201", description: "Saddlery and harness for any animal" },
  { code: "4202", description: "Trunks, suit-cases, vanity-cases, executive-cases, brief-cases, school satchels, spectacle cases, binocular cases, camera cases, musical instrument cases, gun cases, holsters and similar containers; travelling-bags, insulated food or beverages bags, toilet bags, rucksacks, handbags, shopping-bags, wallets, purses, map-cases, cigarette-cases, tobacco-pouches, tool bags, sports bags, bottle-cases, jewellery boxes, powder-boxes, cutlery cases and similar containers, of leather or of composition leather, of sheeting of plastics, of textile materials, of vulcanised fibre or of paperboard" },
  { code: "4203", description: "Articles of apparel and clothing accessories, of leather or of composition leather" },
  { code: "4204", description: "Articles of leather or of composition leather, of a kind used in machinery or mechanical appliances or for other technical uses" },
  { code: "4205", description: "Other articles of leather or of composition leather" },
  { code: "4206", description: "Articles of gut (other than silk-worm gut), of goldbeater's skin, of bladders or of tendons" },
  // Chapter 43 - Furskins and artificial fur; manufactures thereof
  { code: "4301", description: "Raw furskins (including heads, tails, paws and other pieces or cuttings, suitable for furriers use)" },
  { code: "4302", description: "Tanned or dressed furskins (including heads, tails, paws and other pieces or cuttings), unassembled, or assembled (without the addition of other materials) other than those of heading 4303" },
  { code: "4303", description: "Articles of apparel, clothing accessories and other articles of furskin" },
  { code: "4304", description: "Artificial fur and articles thereof" },
  // Chapter 44 - Wood and articles of wood; wood charcoal
  { code: "4401", description: "Fuel wood, in logs, billets, twigs, faggots or similar forms; wood in chips or particles; sawdust and wood waste and scrap" },
  { code: "4402", description: "Wood charcoal (including shell or nut charcoal), whether or not agglomerated" },
  { code: "4403", description: "Wood in the rough, whether or not stripped of bark or sapwood, or roughly squared" },
  { code: "4404", description: "Hoopwood; split poles; piles, pickets and stakes of wood, pointed but not sawn lengthwise" },
  { code: "4405", description: "Wood wool; wood flour" },
  { code: "4406", description: "Railway or tramway sleepers (cross-ties) of wood" },
  { code: "4407", description: "Wood sawn or chipped lengthwise, sliced or peeled, whether or not planed, sanded or end-jointed" },
  { code: "4408", description: "Sheets for veneering (including those obtained by slicing laminated wood), for plywood or for similar laminated wood" },
  { code: "4409", description: "Wood (including strips and friezes for parquet flooring, not assembled) continuously shaped (tongued, grooved, rebated, chamfered, V-jointed, beaded, moulded, rounded or the like) along any of its edges, ends or faces" },
  { code: "4410", description: "Particle board, oriented strand board (OSB) and similar board of wood or other ligneous materials" },
  { code: "4411", description: "Fibreboard of wood or other ligneous materials" },
  { code: "4412", description: "Plywood, veneered panels and similar laminated wood" },
  { code: "4413", description: "Densified wood, in blocks, plates, strips or profile shapes" },
  { code: "4414", description: "Wooden frames for paintings, photographs, mirrors or similar objects" },
  { code: "4415", description: "Packing cases, boxes, crates, drums and similar packings, of wood; cable-drums of wood; pallets, box pallets and other load boards, of wood; pallet collars of wood" },
  { code: "4416", description: "Casks, barrels, vats, tubs and other coopers products and parts thereof, of wood, including staves" },
  { code: "4417", description: "Tools, tool bodies, tool handles, broom or brush bodies and handles, of wood; boot or shoe lasts and trees, of wood" },
  { code: "4418", description: "Builders joinery and carpentry of wood, including cellular wood panels, assembled flooring panels, shingles and shakes" },
  { code: "4419", description: "Tableware and kitchenware, of wood" },
  { code: "4420", description: "Wood marquetry and inlaid wood; caskets and cases for jewellery or cutlery, and similar articles, of wood" },
  { code: "4421", description: "Other articles of wood" },
  // Chapter 47 - Pulp of wood or of other fibrous cellulosic material
  { code: "4701", description: "Mechanical wood pulp" },
  { code: "4702", description: "Chemical wood pulp, dissolving grades" },
  { code: "4703", description: "Chemical wood pulp, soda or sulphate, other than dissolving grades" },
  { code: "4704", description: "Chemical wood pulp, sulphite, other than dissolving grades" },
  { code: "4705", description: "Wood pulp obtained by a combination of mechanical and chemical pulping processes" },
  { code: "4706", description: "Pulps of fibres derived from recovered (waste and scrap) paper or paperboard or of other fibrous cellulosic material" },
  // Chapter 48 - Paper and paperboard; articles of paper pulp, of paper or of paperboard
  { code: "4801", description: "Newsprint, in rolls or sheets" },
  { code: "4802", description: "Uncoated paper and paperboard, of a kind used for writing, printing or other graphic purposes" },
  { code: "4803", description: "Toilet or facial tissue stock, towel or napkin stock and similar paper for household or sanitary purposes" },
  { code: "4804", description: "Uncoated kraft paper and paperboard, in rolls or sheets, other than that of heading 4802 or 4803" },
  { code: "4805", description: "Other uncoated paper and paperboard, in rolls or sheets" },
  { code: "4806", description: "Vegetable parchment, greaseproof papers, tracing papers and glassine and other glazed transparent or translucent papers" },
  { code: "4807", description: "Composite paper and paperboard, not surface-coated or impregnated, in rolls or sheets" },
  { code: "4808", description: "Paper and paperboard, corrugated, creped, crinkled, embossed or perforated, in rolls or sheets" },
  { code: "4809", description: "Carbon paper, self-copy paper and other copying or transfer papers" },
  { code: "4810", description: "Paper and paperboard, coated on one or both sides with kaolin (China clay) or other inorganic substances" },
  { code: "4811", description: "Paper, paperboard, cellulose wadding and webs of cellulose fibres, coated, impregnated, covered, surface-coloured, surface-decorated or printed" },
  { code: "4812", description: "Filter blocks, slabs and plates, of paper pulp" },
  { code: "4813", description: "Cigarette paper, whether or not cut to size or in the form of booklets or tubes" },
  { code: "4814", description: "Wallpaper and similar wall coverings; window transparencies of paper" },
  { code: "4816", description: "Carbon paper, self-copy paper and other copying or transfer papers (other than those of heading 4809)" },
  { code: "4817", description: "Envelopes, letter cards, plain postcards and correspondence cards, of paper or paperboard" },
  { code: "4818", description: "Toilet paper and similar paper, cellulose wadding or webs of cellulose fibres, of a kind used for household or sanitary purposes" },
  { code: "4819", description: "Cartons, boxes, cases, bags and other packing containers, of paper, paperboard, cellulose wadding or webs of cellulose fibres" },
  { code: "4820", description: "Registers, account books, notebooks, order books, receipt books, letter pads, memorandum pads, diaries and similar articles, exercise books, blotting-pads, binders (loose-leaf or other), folders, file covers, manifold business forms, interleaved carbon sets and other articles of stationery" },
  { code: "4821", description: "Paper or paperboard labels of all kinds, whether or not printed" },
  { code: "4822", description: "Bobbins, spools, cops and similar supports of paper pulp, paper or paperboard" },
  { code: "4823", description: "Other paper, paperboard, cellulose wadding and webs of cellulose fibres, cut to size or shape; other articles of paper pulp, paper, paperboard, cellulose wadding or webs of cellulose fibres" },
  // Chapter 49 - Printed books, newspapers, pictures
  { code: "4901", description: "Printed books, brochures, leaflets and similar printed matter" },
  { code: "4902", description: "Newspapers, journals and periodicals, whether or not illustrated or containing advertising material" },
  { code: "4903", description: "Childrens picture, drawing or colouring books" },
  { code: "4904", description: "Music, printed or in manuscript, whether or not bound or illustrated" },
  { code: "4905", description: "Maps and hydrographic or similar charts of all kinds, including atlases, wall maps, topographical plans and globes, printed" },
  { code: "4906", description: "Plans and drawings for architectural, engineering, industrial, commercial, topographical or similar purposes, being originals drawn by hand" },
  { code: "4907", description: "Unused postage, revenue or similar stamps of current or new issue in the country in which they have, or will have, a recognised face value" },
  { code: "4908", description: "Transfers (decalcomanias)" },
  { code: "4909", description: "Printed or illustrated postcards; printed cards bearing personal greetings, messages or announcements" },
  { code: "4910", description: "Calendars of any kind, printed, including calendar blocks" },
  { code: "4911", description: "Other printed matter, including printed pictures and photographs" },
  // Chapter 50-63 - Textiles
  { code: "5001", description: "Silk-worm cocoons suitable for reeling" },
  { code: "5002", description: "Raw silk (not thrown)" },
  { code: "5003", description: "Silk waste (including cocoons unsuitable for reeling, yarn waste and garnetted stock)" },
  { code: "5004", description: "Silk yarn (other than yarn spun from silk waste) not put up for retail sale" },
  { code: "5005", description: "Yarn spun from silk waste, not put up for retail sale" },
  { code: "5006", description: "Silk yarn and yarn spun from silk waste, put up for retail sale; silk-worm gut" },
  { code: "5007", description: "Woven fabrics of silk or of silk waste" },
  { code: "5101", description: "Wool, not carded or combed" },
  { code: "5102", description: "Fine or coarse animal hair, not carded or combed" },
  { code: "5103", description: "Waste of wool or of fine or coarse animal hair" },
  { code: "5105", description: "Wool and fine or coarse animal hair, carded or combed" },
  { code: "5106", description: "Yarn of carded wool, not put up for retail sale" },
  { code: "5107", description: "Yarn of combed wool, not put up for retail sale" },
  { code: "5108", description: "Yarn of fine animal hair (carded or combed), not put up for retail sale" },
  { code: "5109", description: "Yarn of wool or of fine animal hair, put up for retail sale" },
  { code: "5110", description: "Yarn of coarse animal hair or of horsehair (including gimped horsehair yarn)" },
  { code: "5111", description: "Woven fabrics of carded wool or of carded fine animal hair" },
  { code: "5112", description: "Woven fabrics of combed wool or of combed fine animal hair" },
  { code: "5113", description: "Woven fabrics of coarse animal hair or of horsehair" },
  { code: "5201", description: "Cotton, not carded or combed" },
  { code: "5202", description: "Cotton waste (including yarn waste and garnetted stock)" },
  { code: "5203", description: "Cotton, carded or combed" },
  { code: "5204", description: "Cotton sewing thread, whether or not put up for retail sale" },
  { code: "5205", description: "Cotton yarn (other than sewing thread), containing 85% or more by weight of cotton, not put up for retail sale" },
  { code: "5206", description: "Cotton yarn (other than sewing thread), containing less than 85% by weight of cotton, not put up for retail sale" },
  { code: "5207", description: "Cotton yarn (other than sewing thread) put up for retail sale" },
  { code: "5208", description: "Woven fabrics of cotton, containing 85% or more by weight of cotton, weighing not more than 200 g/m²" },
  { code: "5209", description: "Woven fabrics of cotton, containing 85% or more by weight of cotton, weighing more than 200 g/m²" },
  { code: "5210", description: "Woven fabrics of cotton, containing less than 85% by weight of cotton, mixed mainly or solely with man-made fibres, weighing not more than 200 g/m²" },
  { code: "5211", description: "Woven fabrics of cotton, containing less than 85% by weight of cotton, mixed mainly or solely with man-made fibres, weighing more than 200 g/m²" },
  { code: "5212", description: "Other woven fabrics of cotton" },
  { code: "5401", description: "Sewing thread of man-made filaments, whether or not put up for retail sale" },
  { code: "5402", description: "Yarn of synthetic filaments (other than sewing thread), not put up for retail sale" },
  { code: "5403", description: "Yarn of artificial filaments (other than sewing thread), not put up for retail sale" },
  { code: "5404", description: "Synthetic monofilament of 67 decitex or more and of which no cross-sectional dimension exceeds 1 mm" },
  { code: "5405", description: "Artificial monofilament of 67 decitex or more and of which no cross-sectional dimension exceeds 1 mm; strip and the like of artificial textile materials" },
  { code: "5406", description: "Man-made filament yarn (other than sewing thread), put up for retail sale" },
  { code: "5407", description: "Woven fabrics of synthetic filament yarn" },
  { code: "5408", description: "Woven fabrics of artificial filament yarn" },
  { code: "5501", description: "Synthetic filament tow" },
  { code: "5502", description: "Artificial filament tow" },
  { code: "5503", description: "Synthetic staple fibres, not carded, combed or otherwise processed for spinning" },
  { code: "5504", description: "Artificial staple fibres, not carded, combed or otherwise processed for spinning" },
  { code: "5505", description: "Waste (including noils, yarn waste and garnetted stock) of man-made fibres" },
  { code: "5506", description: "Synthetic staple fibres, carded, combed or otherwise processed for spinning" },
  { code: "5507", description: "Artificial staple fibres, carded, combed or otherwise processed for spinning" },
  { code: "5508", description: "Sewing thread of man-made staple fibres, whether or not put up for retail sale" },
  { code: "5509", description: "Yarn (other than sewing thread) of synthetic staple fibres, not put up for retail sale" },
  { code: "5510", description: "Yarn (other than sewing thread) of artificial staple fibres, not put up for retail sale" },
  { code: "5511", description: "Yarn (other than sewing thread) of man-made staple fibres, put up for retail sale" },
  { code: "5512", description: "Woven fabrics of synthetic staple fibres, containing 85% or more by weight of synthetic staple fibres" },
  { code: "5513", description: "Woven fabrics of synthetic staple fibres, containing less than 85% by weight of such fibres, mixed mainly or solely with cotton, of a weight not exceeding 170 g/m²" },
  { code: "5514", description: "Woven fabrics of synthetic staple fibres, containing less than 85% by weight of such fibres, mixed mainly or solely with cotton, of a weight exceeding 170 g/m²" },
  { code: "5515", description: "Other woven fabrics of synthetic staple fibres" },
  { code: "5516", description: "Woven fabrics of artificial staple fibres" },
  { code: "5601", description: "Wadding of textile materials and articles thereof; textile fibres, not exceeding 5 mm in length (flock)" },
  { code: "5602", description: "Felt, whether or not impregnated, coated, covered or laminated" },
  { code: "5603", description: "Nonwovens, whether or not impregnated, coated, covered or laminated" },
  { code: "5604", description: "Rubber thread and cord, textile covered; textile yarn, and strip and the like, impregnated, coated, covered or sheathed with rubber or plastics" },
  { code: "5605", description: "Metallised yarn, whether or not gimped, being textile yarn, or strip or the like of heading 5404 or 5405, combined with metal in the form of thread, strip or powder or covered with metal" },
  { code: "5606", description: "Gimped yarn, and strip and the like of heading 5404 or 5405, gimped (other than those of heading 5605 and gimped horsehair yarn)" },
  { code: "5607", description: "Twine, cordage, ropes and cables, whether or not plaited or braided and whether or not impregnated, coated, covered or sheathed with rubber or plastics" },
  { code: "5608", description: "Knotted netting of twine, cordage or rope; made up fishing nets and other made up nets, of textile materials" },
  { code: "5609", description: "Articles of yarn, strip or the like of heading 5404 or 5405, twine, cordage, rope or cables, not elsewhere specified or included" },
  { code: "5701", description: "Carpets and other textile floor coverings, knotted, whether or not made up" },
  { code: "5702", description: "Carpets and other textile floor coverings, woven, not tufted or flocked, whether or not made up" },
  { code: "5703", description: "Carpets and other textile floor coverings, tufted, whether or not made up" },
  { code: "5704", description: "Carpets and other textile floor coverings, of felt, not tufted or flocked, whether or not made up" },
  { code: "5705", description: "Other carpets and other textile floor coverings, whether or not made up" },
  { code: "5801", description: "Woven pile fabrics and chenille fabrics, other than fabrics of heading 5802 or 5806" },
  { code: "5802", description: "Terry towelling and similar woven terry fabrics, other than narrow fabrics of heading 5806; tufted textile fabrics, other than products of heading 5703" },
  { code: "5803", description: "Gauze, other than narrow fabrics of heading 5806" },
  { code: "5804", description: "Tulles and other net fabrics, not including woven, knitted or crocheted fabrics; lace in the piece, in strips or in motifs" },
  { code: "5805", description: "Hand-woven tapestries of the type Gobelins, Flanders, Aubusson, Beauvais and the like, and needle-worked tapestries" },
  { code: "5806", description: "Narrow woven fabrics, other than goods of heading 5807; narrow fabrics consisting of warp without weft assembled by means of an adhesive (bolducs)" },
  { code: "5807", description: "Labels, badges and similar articles of textile materials, in the piece, in strips or cut to shape or size, not embroidered" },
  { code: "5808", description: "Braids in the piece; ornamental trimmings in the piece, without embroidery, other than knitted or crocheted; tassels, pompons and similar articles" },
  { code: "5809", description: "Woven fabrics of metal thread and woven fabrics of metallised yarn of heading 5605" },
  { code: "5810", description: "Embroidery in the piece, in strips or in motifs" },
  { code: "5811", description: "Quilted textile products in the piece, composed of one or more layers of textile materials assembled with padding by stitching or otherwise, other than embroidery of heading 5810" },
  { code: "5901", description: "Textile fabrics coated with gum or amylaceous substances" },
  { code: "5902", description: "Tyre cord fabric of high tenacity yarn of nylon or other polyamides, polyesters or viscose rayon" },
  { code: "5903", description: "Textile fabrics impregnated, coated, covered or laminated with plastics, other than those of heading 5902" },
  { code: "5904", description: "Linoleum, whether or not cut to shape; floor coverings consisting of a coating or covering applied on a textile backing, whether or not cut to shape" },
  { code: "5905", description: "Textile wall coverings" },
  { code: "5906", description: "Rubberised textile fabrics, other than those of heading 5902" },
  { code: "5907", description: "Textile fabrics otherwise impregnated, coated or covered; painted canvas being theatrical scenery, studio back-cloths or the like" },
  { code: "5908", description: "Textile wicks, woven, plaited or knitted, for lamps, stoves, lighters, candles or the like" },
  { code: "5909", description: "Textile hosepiping and similar textile tubing, with or without lining, armour or accessories of other materials" },
  { code: "5910", description: "Transmission or conveyor belts or belting, of textile material, whether or not impregnated, coated, covered or laminated with plastics, or reinforced with metal or other material" },
  { code: "5911", description: "Textile products and articles, for technical uses" },
  { code: "6001", description: "Pile fabrics, including long pile fabrics and terry fabrics, knitted or crocheted" },
  { code: "6002", description: "Knitted or crocheted fabrics of a width not exceeding 30 cm" },
  { code: "6003", description: "Knitted or crocheted fabrics of a width not exceeding 30 cm" },
  { code: "6004", description: "Knitted or crocheted fabrics of a width exceeding 30 cm, containing by weight 5% or more of elastomeric yarn or rubber thread" },
  { code: "6005", description: "Warp knit fabrics (including those made on galloon knitting machines), other than those of headings 6001 to 6004" },
  { code: "6006", description: "Other knitted or crocheted fabrics" },
  { code: "6101", description: "Men's or boys' overcoats, car-coats, capes, cloaks, anoraks (including ski-jackets), wind-cheaters, wind-jackets and similar articles, knitted or crocheted" },
  { code: "6102", description: "Women's or girls' overcoats, car-coats, capes, cloaks, anoraks (including ski-jackets), wind-cheaters, wind-jackets and similar articles, knitted or crocheted" },
  { code: "6103", description: "Men's or boys' suits, ensembles, jackets, blazers, trousers, bib and brace overalls, breeches and shorts (other than swimwear), knitted or crocheted" },
  { code: "6104", description: "Women's or girls' suits, ensembles, jackets, blazers, dresses, skirts, divided skirts, trousers, bib and brace overalls, breeches and shorts (other than swimwear), knitted or crocheted" },
  { code: "6105", description: "Men's or boys' shirts, knitted or crocheted" },
  { code: "6106", description: "Women's or girls' blouses, shirts and shirt-blouses, knitted or crocheted" },
  { code: "6107", description: "Men's or boys' underpants, briefs, nightshirts, pyjamas, bathrobes, dressing gowns and similar articles, knitted or crocheted" },
  { code: "6108", description: "Women's or girls' slips, petticoats, briefs, panties, nightdresses, pyjamas, negligees, bathrobes, dressing gowns and similar articles, knitted or crocheted" },
  { code: "6109", description: "T-shirts, singlets and other vests, knitted or crocheted" },
  { code: "6110", description: "Jerseys, pullovers, sweatshirts, waistcoats (vests) and similar articles, knitted or crocheted" },
  { code: "6111", description: "Babies' garments and clothing accessories, knitted or crocheted" },
  { code: "6112", description: "Track suits, ski suits and swimwear, knitted or crocheted" },
  { code: "6113", description: "Garments, made up of knitted or crocheted fabrics of heading 5903, 5906 or 5907" },
  { code: "6114", description: "Other garments, knitted or crocheted" },
  { code: "6115", description: "Pantyhose, tights, stockings, socks and other hosiery, including graduated compression hosiery, knitted or crocheted" },
  { code: "6116", description: "Gloves, mittens and mitts, knitted or crocheted" },
  { code: "6117", description: "Other made up clothing accessories, knitted or crocheted; knitted or crocheted parts of garments or of clothing accessories" },
  { code: "6201", description: "Men's or boys' overcoats, car-coats, capes, cloaks, anoraks (including ski-jackets), wind-cheaters, wind-jackets and similar articles" },
  { code: "6202", description: "Women's or girls' overcoats, car-coats, capes, cloaks, anoraks (including ski-jackets), wind-cheaters, wind-jackets and similar articles" },
  { code: "6203", description: "Men's or boys' suits, ensembles, jackets, blazers, trousers, bib and brace overalls, breeches and shorts (other than swimwear)" },
  { code: "6204", description: "Women's or girls' suits, ensembles, jackets, blazers, dresses, skirts, divided skirts, trousers, bib and brace overalls, breeches and shorts (other than swimwear)" },
  { code: "6205", description: "Men's or boys' shirts" },
  { code: "6206", description: "Women's or girls' blouses, shirts and shirt-blouses" },
  { code: "6207", description: "Men's or boys' singlets and other vests, underpants, briefs, nightshirts, pyjamas, bathrobes, dressing gowns and similar articles" },
  { code: "6208", description: "Women's or girls' singlets and other vests, slips, petticoats, briefs, panties, nightdresses, pyjamas, negligees, bathrobes, dressing gowns and similar articles" },
  { code: "6209", description: "Babies' garments and clothing accessories" },
  { code: "6210", description: "Garments, made up of fabrics of heading 5602, 5603, 5903, 5906 or 5907" },
  { code: "6211", description: "Track suits, ski suits and swimwear; other garments" },
  { code: "6212", description: "Brassieres, girdles, corsets, braces, suspenders, garters and similar articles and parts thereof" },
  { code: "6213", description: "Handkerchiefs" },
  { code: "6214", description: "Shawls, scarves, mufflers, mantillas, veils and the like" },
  { code: "6215", description: "Ties, bow ties and cravats" },
  { code: "6216", description: "Gloves, mittens and mitts" },
  { code: "6217", description: "Other made up clothing accessories; parts of garments or of clothing accessories, other than those of heading 6212" },
  { code: "6301", description: "Blankets and travelling rugs" },
  { code: "6302", description: "Bed linen, table linen, toilet linen and kitchen linen" },
  { code: "6303", description: "Curtains (including drapes) and interior blinds; curtain or bed valances" },
  { code: "6304", description: "Other furnishing articles, excluding those of heading 9404" },
  { code: "6305", description: "Sacks and bags, of a kind used for the packing of goods" },
  { code: "6306", description: "Tarpaulins, awnings and sunblinds; tents; sails for boats, sailboards or land craft; camping goods" },
  { code: "6307", description: "Other made up articles, including dress patterns" },
  { code: "6308", description: "Sets consisting of woven fabric and yarn, whether or not with accessories, for making up into rugs, tapestries, embroidered table cloths or serviettes, or similar textile articles, put up in packings for retail sale" },
  { code: "6309", description: "Worn clothing and other worn articles" },
  { code: "6310", description: "Used or new rags, scrap twine, cordage, rope and cables and worn out articles of twine, cordage, rope or cables, of textile materials" },
  // Chapter 64 - Footwear
  { code: "6401", description: "Waterproof footwear with outer soles and uppers of rubber or of plastics, the uppers of which are neither fixed to the sole nor assembled by stitching, riveting, nailing, screwing, plugging or similar processes" },
  { code: "6402", description: "Other footwear with outer soles and uppers of rubber or plastics" },
  { code: "6403", description: "Footwear with outer soles of rubber, plastics, leather or composition leather and uppers of leather" },
  { code: "6404", description: "Footwear with outer soles of rubber, plastics, leather or composition leather and uppers of textile materials" },
  { code: "6405", description: "Other footwear" },
  { code: "6406", description: "Parts of footwear (including uppers whether or not attached to soles other than outer soles); removable in-soles, heel cushions and similar articles; gaiters, leggings and similar articles, and parts thereof" },
  // Chapter 65 - Headgear and parts thereof
  { code: "6501", description: "Hat-forms, hat bodies and hoods of felt, neither blocked to shape nor with made brims; plateaux and manchons (including slit manchons), of felt" },
  { code: "6502", description: "Hat-shapes, plaited or made by assembling strips of any material, neither blocked to shape, nor with made brims, nor lined, nor trimmed" },
  { code: "6504", description: "Hats and other headgear, plaited or made by assembling strips of any material, whether or not lined or trimmed" },
  { code: "6505", description: "Hats and other headgear, knitted or crocheted, or made up from lace, felt or other textile fabric, in the piece (but not in strips)" },
  { code: "6506", description: "Other headgear, whether or not lined or trimmed" },
  { code: "6507", description: "Head-bands, linings, covers, hat foundations, hat frames, peaks and chinstraps, for headgear" },
  // Chapter 68 - Articles of stone, plaster, cement, asbestos, mica
  { code: "6801", description: "Setts, curbstones and flagstones, of natural stone (except slate)" },
  { code: "6802", description: "Worked monumental or building stone (except slate) and articles thereof, other than goods of heading 6801" },
  { code: "6803", description: "Worked slate and articles of slate or of agglomerated slate" },
  { code: "6804", description: "Millstones, grindstones, grinding wheels and the like, without frameworks, for grinding, sharpening, polishing, trueing or cutting" },
  { code: "6805", description: "Natural or artificial abrasive powder or grain, on a base of textile material, of paper, of paperboard or of other materials" },
  { code: "6806", description: "Slag wool, rock wool and similar mineral wools; exfoliated vermiculite, expanded clays, foamed slag and similar expanded mineral materials" },
  { code: "6807", description: "Articles of asphalt or of similar material (for example, petroleum bitumen or coal tar pitch)" },
  { code: "6808", description: "Panels, boards, tiles, blocks and similar articles of vegetable fibre, of straw or of shavings, chips, particles, sawdust or other waste, of wood, agglomerated with cement, plaster or other mineral binders" },
  { code: "6809", description: "Articles of plaster or of compositions based on plaster" },
  { code: "6810", description: "Articles of cement, of concrete or of artificial stone, whether or not reinforced" },
  { code: "6811", description: "Articles of asbestos-cement, of cellulose fibre-cement or the like" },
  { code: "6812", description: "Fabricated asbestos fibres; mixtures with a basis of asbestos or with a basis of asbestos and magnesium carbonate; articles of such mixtures or of asbestos" },
  { code: "6813", description: "Friction material and articles thereof (for example, sheets, rolls, strips, segments, discs, washers, pads), not mounted, for brakes, for clutches or the like" },
  { code: "6814", description: "Worked mica and articles of mica, including agglomerated or reconstituted mica, whether or not on a support of paper, paperboard or other materials" },
  { code: "6815", description: "Articles of stone or of other mineral substances (including carbon fibres, articles of carbon fibres and articles of peat), not elsewhere specified or included" },
  // Chapter 69 - Ceramic products
  { code: "6901", description: "Bricks, blocks, tiles and other ceramic goods of siliceous fossil meals" },
  { code: "6902", description: "Refractory bricks, blocks, tiles and similar refractory ceramic constructional goods" },
  { code: "6903", description: "Other refractory ceramic goods (for example, retorts, crucibles, muffles, nozzles, plugs, supports, cupels, tubes, pipes, sheaths and rods)" },
  { code: "6904", description: "Ceramic building bricks, flooring blocks, support or filler tiles and the like" },
  { code: "6905", description: "Roofing tiles, chimney-pots, cowls, chimney liners, architectural ornaments and other ceramic constructional goods" },
  { code: "6906", description: "Ceramic pipes, conduits, guttering and pipe fittings" },
  { code: "6907", description: "Unglazed ceramic flags and paving, hearth or wall tiles; unglazed ceramic mosaic cubes and the like" },
  { code: "6908", description: "Glazed ceramic flags and paving, hearth or wall tiles; glazed ceramic mosaic cubes and the like" },
  { code: "6909", description: "Ceramic wares for laboratory, chemical or other technical uses; ceramic troughs, tubs and similar receptacles used in agriculture" },
  { code: "6910", description: "Ceramic sinks, wash basins, wash basin pedestals, baths, bidets, water closet pans, flushing cisterns, urinals and similar sanitary fixtures" },
  { code: "6911", description: "Tableware, kitchenware, other household articles and toilet articles, of porcelain or china" },
  { code: "6912", description: "Ceramic tableware, kitchenware, other household articles and toilet articles, other than of porcelain or china" },
  { code: "6913", description: "Statuettes and other ornamental ceramic articles" },
  { code: "6914", description: "Other ceramic articles" },
  // Chapter 70 - Glass and glassware
  { code: "7001", description: "Cullet and other waste and scrap of glass; glass in the mass" },
  { code: "7002", description: "Glass in balls (other than microspheres of heading 7018), rods or tubes, unworked" },
  { code: "7003", description: "Cast glass and rolled glass, in sheets or profiles, whether or not having an absorbent, reflecting or non-reflecting layer" },
  { code: "7004", description: "Drawn glass and blown glass, in sheets, whether or not having an absorbent, reflecting or non-reflecting layer" },
  { code: "7005", description: "Float glass and surface ground or polished glass, in sheets, whether or not having an absorbent, reflecting or non-reflecting layer, but not otherwise worked" },
  { code: "7006", description: "Glass of heading 7003, 7004 or 7005, bent, edge-worked, engraved, drilled, enamelled or otherwise worked, but not framed or fitted with other materials" },
  { code: "7007", description: "Safety glass, consisting of toughened (tempered) or laminated glass" },
  { code: "7008", description: "Multiple-walled insulating units of glass" },
  { code: "7009", description: "Glass mirrors, whether or not framed, including rear-view mirrors" },
  { code: "7010", description: "Carboys, bottles, flasks, jars, pots, phials, ampoules and other containers, of glass, of a kind used for the conveyance or packing of goods; preserving jars of glass; stoppers, lids and other closures, of glass" },
  { code: "7011", description: "Glass envelopes (including bulbs and tubes), open, and glass parts thereof, without fittings, for electric lamps, cathode-ray tubes or the like" },
  { code: "7013", description: "Glassware of a kind used for table, kitchen, toilet, office, indoor decoration or similar purposes (other than that of heading 7010 or 7018)" },
  { code: "7014", description: "Signalling glassware and optical elements of glass (other than those of heading 7015), not optically worked" },
  { code: "7015", description: "Clock or watch glasses and similar glasses, glasses for non-corrective or corrective spectacles, curved, bent, hollowed or the like, not optically worked" },
  { code: "7016", description: "Paving blocks, slabs, bricks, squares, tiles and other articles of pressed or moulded glass, whether or not wired, of a kind used for building or construction purposes" },
  { code: "7017", description: "Laboratory, hygienic or pharmaceutical glassware, whether or not graduated or calibrated" },
  { code: "7018", description: "Glass beads, imitation pearls, imitation precious or semi-precious stones and similar glass smallwares, and articles thereof other than imitation jewellery" },
  { code: "7019", description: "Glass fibres (including glass wool) and articles thereof" },
  { code: "7020", description: "Other articles of glass" },
  // Chapter 71 - Natural or cultured pearls, precious or semi-precious stones, precious metals
  { code: "7101", description: "Pearls, natural or cultured, whether or not worked or graded but not strung, mounted or set" },
  { code: "7102", description: "Diamonds, whether or not worked, but not mounted or set" },
  { code: "7103", description: "Precious stones (other than diamonds) and semi-precious stones, whether or not worked or graded but not strung, mounted or set" },
  { code: "7104", description: "Synthetic or reconstructed precious or semi-precious stones, whether or not worked or graded but not strung, mounted or set" },
  { code: "7105", description: "Dust and powder of natural or synthetic precious or semi-precious stones" },
  { code: "7106", description: "Silver (including silver plated with gold or platinum), unwrought or in semi-manufactured forms, or in powder form" },
  { code: "7107", description: "Base metals clad with silver, not further worked than semi-manufactured" },
  { code: "7108", description: "Gold (including gold plated with platinum) unwrought or in semi-manufactured forms, or in powder form" },
  { code: "7109", description: "Base metals or silver, clad with gold, not further worked than semi-manufactured" },
  { code: "7110", description: "Platinum, unwrought or in semi-manufactured forms, or in powder form" },
  { code: "7111", description: "Base metals, silver or gold, clad with platinum, not further worked than semi-manufactured" },
  { code: "7112", description: "Waste and scrap of precious metal or of metal clad with precious metal; other waste and scrap containing precious metal or precious metal compounds" },
  { code: "7113", description: "Articles of jewellery and parts thereof, of precious metal or of metal clad with precious metal" },
  { code: "7114", description: "Articles of goldsmiths or silversmiths wares and parts thereof, of precious metal or of metal clad with precious metal" },
  { code: "7115", description: "Other articles of precious metal or of metal clad with precious metal" },
  { code: "7116", description: "Articles of natural or cultured pearls, precious or semi-precious stones (natural, synthetic or reconstructed)" },
  { code: "7117", description: "Imitation jewellery" },
  { code: "7118", description: "Coin" },
  // Chapter 72 - Iron and steel
  { code: "7201", description: "Pig iron and spiegeleisen in pigs, blocks or other primary forms" },
  { code: "7202", description: "Ferro-alloys" },
  { code: "7203", description: "Ferrous products obtained by direct reduction of iron ore and other spongy ferrous products" },
  { code: "7204", description: "Ferrous waste and scrap; remelting scrap ingots of iron or steel" },
  { code: "7205", description: "Granules and powders, of pig iron, spiegeleisen, iron or steel" },
  { code: "7206", description: "Iron and non-alloy steel in ingots or other primary forms (excluding iron of heading 7203)" },
  { code: "7207", description: "Semi-finished products of iron or non-alloy steel" },
  { code: "7208", description: "Flat-rolled products of iron or non-alloy steel, of a width of 600 mm or more, hot-rolled, not clad, plated or coated" },
  { code: "7209", description: "Flat-rolled products of iron or non-alloy steel, of a width of 600 mm or more, cold-rolled (cold-reduced), not clad, plated or coated" },
  { code: "7210", description: "Flat-rolled products of iron or non-alloy steel, of a width of 600 mm or more, clad, plated or coated" },
  { code: "7211", description: "Flat-rolled products of iron or non-alloy steel, of a width of less than 600 mm, not clad, plated or coated" },
  { code: "7212", description: "Flat-rolled products of iron or non-alloy steel, of a width of less than 600 mm, clad, plated or coated" },
  { code: "7213", description: "Bars and rods, hot-rolled, in irregularly wound coils, of iron or non-alloy steel" },
  { code: "7214", description: "Other bars and rods of iron or non-alloy steel, not further worked than forged, hot-rolled, hot-drawn or hot-extruded, but including those twisted after rolling" },
  { code: "7215", description: "Other bars and rods of iron or non-alloy steel" },
  { code: "7216", description: "Angles, shapes and sections of iron or non-alloy steel" },
  { code: "7217", description: "Wire of iron or non-alloy steel" },
  { code: "7218", description: "Stainless steel in ingots or other primary forms; semi-finished products of stainless steel" },
  { code: "7219", description: "Flat-rolled products of stainless steel, of a width of 600 mm or more" },
  { code: "7220", description: "Flat-rolled products of stainless steel, of a width of less than 600 mm" },
  { code: "7221", description: "Bars and rods, hot-rolled, in irregularly wound coils, of stainless steel" },
  { code: "7222", description: "Other bars and rods of stainless steel; angles, shapes and sections of stainless steel" },
  { code: "7223", description: "Wire of stainless steel" },
  { code: "7224", description: "Other alloy steel in ingots or other primary forms; semi-finished products of other alloy steel" },
  { code: "7225", description: "Flat-rolled products of other alloy steel, of a width of 600 mm or more" },
  { code: "7226", description: "Flat-rolled products of other alloy steel, of a width of less than 600 mm" },
  { code: "7227", description: "Bars and rods, hot-rolled, in irregularly wound coils, of other alloy steel" },
  { code: "7228", description: "Other bars and rods of other alloy steel; angles, shapes and sections, of other alloy steel; hollow drill bars and rods, of alloy or non-alloy steel" },
  { code: "7229", description: "Wire of other alloy steel" },
  { code: "7301", description: "Sheet piling of iron or steel, whether or not drilled, punched or made from assembled elements; welded angles, shapes and sections, of iron or steel" },
  { code: "7302", description: "Railway or tramway track construction material of iron or steel" },
  { code: "7303", description: "Tubes, pipes and hollow profiles, of cast iron" },
  { code: "7304", description: "Tubes, pipes and hollow profiles, seamless, of iron (other than cast iron) or steel" },
  { code: "7305", description: "Other tubes and pipes (for example, welded, riveted or similarly closed), having circular cross-sections, the external diameter of which exceeds 406.4 mm, of iron or steel" },
  { code: "7306", description: "Other tubes, pipes and hollow profiles (for example, open seam or welded, riveted or similarly closed), of iron or steel" },
  { code: "7307", description: "Tube or pipe fittings (for example, couplings, elbows, sleeves), of iron or steel" },
  { code: "7308", description: "Structures (excluding prefabricated buildings of heading 9406) and parts of structures (for example, bridges and bridge-sections, lock-gates, towers, lattice masts, roofs, roofing frame-works, doors and windows and their frames and thresholds for doors, shutters, balustrades, pillars and columns), of iron or steel" },
  { code: "7309", description: "Reservoirs, tanks, vats and similar containers for any material (other than compressed or liquefied gas), of iron or steel, of a capacity exceeding 300 l" },
  { code: "7310", description: "Tanks, casks, drums, cans, boxes and similar containers, for any material (other than compressed or liquefied gas), of iron or steel, of a capacity not exceeding 300 l" },
  { code: "7311", description: "Containers for compressed or liquefied gas, of iron or steel" },
  { code: "7312", description: "Stranded wire, ropes, cables, plaited bands, slings and the like, of iron or steel, not electrically insulated" },
  { code: "7313", description: "Barbed wire of iron or steel; twisted hoop or single flat wire, barbed or not, and loosely twisted double wire, of a kind used for fencing, of iron or steel" },
  { code: "7314", description: "Cloth (including endless bands), grill, netting and fencing, of iron or steel wire; expanded metal of iron or steel" },
  { code: "7315", description: "Chain and parts thereof, of iron or steel" },
  { code: "7316", description: "Anchors, grapnels and parts thereof, of iron or steel" },
  { code: "7317", description: "Nails, tacks, drawing pins, corrugated nails, staples (other than those of heading 8305) and similar articles, of iron or steel" },
  { code: "7318", description: "Screws, bolts, nuts, coach screws, screw hooks, rivets, cotters, cotter-pins, washers (including spring washers) and similar articles, of iron or steel" },
  { code: "7319", description: "Sewing needles, knitting needles, bodkins, crochet hooks, embroidery stilettos and similar articles, for use in the hand, of iron or steel" },
  { code: "7320", description: "Springs and leaves for springs, of iron or steel" },
  { code: "7321", description: "Stoves, ranges, grates, cookers (including those with subsidiary boilers for central heating), barbecues, braziers, gas-rings, plate warmers and similar non-electric domestic appliances, and parts thereof, of iron or steel" },
  { code: "7322", description: "Radiators for central heating, not electrically heated, and parts thereof, of iron or steel; air heaters and hot air distributors (including distributors which can also distribute fresh or conditioned air)" },
  { code: "7323", description: "Table, kitchen or other household articles and parts thereof, of iron or steel; iron or steel wool; pot scourers and scouring or polishing pads, gloves and the like, of iron or steel" },
  { code: "7324", description: "Sanitary ware and parts thereof, of iron or steel" },
  { code: "7325", description: "Other cast articles of iron or steel" },
  { code: "7326", description: "Other articles of iron or steel" },
  // Chapter 74 - Copper and articles thereof
  { code: "7401", description: "Copper mattes; cement copper (precipitated copper)" },
  { code: "7402", description: "Unrefined copper; copper anodes for electrolytic refining" },
  { code: "7403", description: "Refined copper and copper alloys, unwrought" },
  { code: "7404", description: "Copper waste and scrap" },
  { code: "7405", description: "Master alloys of copper" },
  { code: "7406", description: "Copper powders and flakes" },
  { code: "7407", description: "Copper bars, rods and profiles" },
  { code: "7408", description: "Copper wire" },
  { code: "7409", description: "Copper plates, sheets and strip, of a thickness exceeding 0.15 mm" },
  { code: "7410", description: "Copper foil (whether or not printed or backed with paper, paperboard, plastics or similar backing materials) of a thickness (excluding any backing) not exceeding 0.15 mm" },
  { code: "7411", description: "Copper tubes and pipes" },
  { code: "7412", description: "Copper tube or pipe fittings (for example, couplings, elbows, sleeves)" },
  { code: "7413", description: "Stranded wire, cables, plaited bands and the like, of copper, not electrically insulated" },
  { code: "7415", description: "Nails, tacks, drawing pins, staples (other than those of heading 8305) and similar articles, of copper or of iron or steel with heads of copper" },
  { code: "7416", description: "Springs, of copper" },
  { code: "7417", description: "Cooking or heating apparatus of a kind used for domestic purposes, non-electric, and parts thereof, of copper" },
  { code: "7418", description: "Table, kitchen or other household articles and parts thereof, of copper; pot scourers and scouring or polishing pads, gloves and the like, of copper; sanitary ware and parts thereof, of copper" },
  { code: "7419", description: "Other articles of copper" },
  // Chapter 76 - Aluminium and articles thereof
  { code: "7601", description: "Unwrought aluminium" },
  { code: "7602", description: "Aluminium waste and scrap" },
  { code: "7603", description: "Aluminium powders and flakes" },
  { code: "7604", description: "Aluminium bars, rods and profiles" },
  { code: "7605", description: "Aluminium wire" },
  { code: "7606", description: "Aluminium plates, sheets and strip, of a thickness exceeding 0.2 mm" },
  { code: "7607", description: "Aluminium foil (whether or not printed or backed with paper, paperboard, plastics or similar backing materials) of a thickness (excluding any backing) not exceeding 0.2 mm" },
  { code: "7608", description: "Aluminium tubes and pipes" },
  { code: "7609", description: "Aluminium tube or pipe fittings (for example, couplings, elbows, sleeves)" },
  { code: "7610", description: "Aluminium structures (excluding prefabricated buildings of heading 9406) and parts of structures (for example, bridges and bridge-sections, towers, lattice masts, roofs, roofing frameworks, doors and windows and their frames and thresholds for doors, balustrades, pillars and columns); aluminium plates, rods, profiles, tubes and the like, prepared for use in structures" },
  { code: "7611", description: "Aluminium reservoirs, tanks, vats and similar containers, for any material (other than compressed or liquefied gas), of a capacity exceeding 300 l" },
  { code: "7612", description: "Aluminium casks, drums, cans, boxes and similar containers (including rigid or collapsible tubular containers), for any material (other than compressed or liquefied gas), of a capacity not exceeding 300 l" },
  { code: "7613", description: "Aluminium containers for compressed or liquefied gas" },
  { code: "7614", description: "Stranded wire, cables, plaited bands and the like, of aluminium, not electrically insulated" },
  { code: "7615", description: "Table, kitchen or other household articles and parts thereof, of aluminium; pot scourers and scouring or polishing pads, gloves and the like, of aluminium; sanitary ware and parts thereof, of aluminium" },
  { code: "7616", description: "Other articles of aluminium" },
  // Chapter 82-83 - Tools, cutlery, misc metal articles
  { code: "8201", description: "Hand tools, the following: spades, shovels, mattocks, picks, hoes, forks and rakes" },
  { code: "8202", description: "Hand saws; blades for saws of all kinds (including slitting, slotting or toothless saw blades)" },
  { code: "8203", description: "Files, rasps, pliers (including cutting pliers), pincers, tweezers, metal cutting shears, pipe-cutters, bolt croppers, perforating punches and similar hand tools" },
  { code: "8204", description: "Hand-operated spanners and wrenches (including torque meter wrenches but not including tap wrenches); interchangeable spanner sockets, with or without handles" },
  { code: "8205", description: "Hand tools (including glaziers diamonds), not elsewhere specified or included; blow lamps; vices, clamps and the like, other than accessories for and parts of, machine tools" },
  { code: "8206", description: "Tools of two or more of the headings 8202 to 8205, put up in sets for retail sale" },
  { code: "8207", description: "Interchangeable tools for hand tools, whether or not power-operated, or for machine-tools (for example, for pressing, stamping, punching, tapping, threading, drilling, boring, broaching, milling, turning or screw driving)" },
  { code: "8208", description: "Knives and cutting blades, for machines or for mechanical appliances" },
  { code: "8209", description: "Plates, sticks, tips and the like for tools, unmounted, of cermets" },
  { code: "8210", description: "Hand-operated mechanical appliances, weighing 10 kg or less, used in the preparation, conditioning or serving of food or drink" },
  { code: "8211", description: "Knives with cutting blades, serrated or not (including pruning knives), other than knives of heading 8208, and blades therefor" },
  { code: "8212", description: "Razors and razor blades (including razor blade blanks in strips)" },
  { code: "8213", description: "Scissors, tailors shears and similar shears, and blades therefor" },
  { code: "8214", description: "Other articles of cutlery (for example, hair clippers, butchers or kitchen cleavers, choppers and mincing knives, paper knives)" },
  { code: "8215", description: "Spoons, forks, ladles, skimmers, cake-servers, fish-knives, butter-knives, sugar tongs and similar kitchen or tableware" },
  { code: "8301", description: "Padlocks and locks (key, combination or electrically operated), of base metal; clasps and frames with clasps, incorporating locks, of base metal; keys for any of the foregoing articles, of base metal" },
  { code: "8302", description: "Base metal mountings, fittings and similar articles suitable for furniture, doors, staircases, windows, blinds, coachwork, saddlery, trunks, chests, caskets or the like" },
  { code: "8303", description: "Armoured or reinforced safes, strong-boxes and doors and safe deposit lockers for strong-rooms, cash or deed boxes and the like, of base metal" },
  { code: "8304", description: "Filing cabinets, card-index cabinets, paper trays, paper rests, pen trays, office-stamp stands and similar office or desk equipment, of base metal, other than office furniture of heading 9403" },
  { code: "8305", description: "Fittings for loose-leaf binders or files, letter clips, letter corners, paper clips, indexing tags and similar office articles, of base metal; staples in strips (for example, for offices, upholstery, packaging), of base metal" },
  { code: "8306", description: "Bells, gongs and the like, non-electric, of base metal; statuettes and other ornaments, of base metal; photograph, picture or similar frames, of base metal; mirrors of base metal" },
  { code: "8307", description: "Flexible tubing of base metal, with or without fittings" },
  { code: "8308", description: "Clasps, frames with clasps, buckles, buckle-clasps, hooks, eyes, eyelets and the like, of base metal, of a kind used for clothing, footwear, awnings, handbags, travel goods or other made up articles, tubular or bifurcated rivets, of base metal; beads and spangles, of base metal" },
  { code: "8309", description: "Stoppers, caps and lids (including crown corks, screw caps and pouring stoppers), capsules for bottles, threaded bungs, bung covers, seals and other packing accessories, of base metal" },
  { code: "8310", description: "Sign-plates, name-plates, address-plates and similar plates, numbers, letters and other symbols, of base metal, excluding those of heading 9405" },
  { code: "8311", description: "Wire, rods, tubes, plates, electrodes and similar products, of base metal or of metal carbides, coated or cored with flux material, of a kind used for soldering, brazing, welding or deposition of metal or of metal carbides; wire and rods, of agglomerated base metal powder, used for metal spraying" },
  // Chapter 84 - Nuclear reactors, boilers, machinery and mechanical appliances
  { code: "8401", description: "Nuclear reactors; fuel elements (cartridges), non-irradiated, for nuclear reactors; machinery and apparatus for isotopic separation" },
  { code: "8402", description: "Steam or other vapour generating boilers (other than central heating hot water boilers capable also of producing low pressure steam)" },
  { code: "8403", description: "Central heating boilers other than those of heading 8402" },
  { code: "8404", description: "Auxiliary plant for use with boilers of heading 8402 or 8403 (for example, economisers, super-heaters, soot removers, gas recoverers); condensers for steam or other vapour power units" },
  { code: "8405", description: "Producer gas or water gas generators, with or without their purifiers; acetylene gas generators and similar water process gas generators, with or without their purifiers" },
  { code: "8406", description: "Steam turbines and other vapour turbines" },
  { code: "8407", description: "Spark-ignition reciprocating or rotary internal combustion piston engines" },
  { code: "8408", description: "Compression-ignition internal combustion piston engines (diesel or semi-diesel engines)" },
  { code: "8409", description: "Parts suitable for use solely or principally with the engines of heading 8407 or 8408" },
  { code: "8410", description: "Hydraulic turbines, water wheels, and regulators therefor" },
  { code: "8411", description: "Turbo-jets, turbo-propellers and other gas turbines" },
  { code: "8412", description: "Other engines and motors" },
  { code: "8413", description: "Pumps for liquids, whether or not fitted with a measuring device; liquid elevators" },
  { code: "8414", description: "Air or vacuum pumps, air or other gas compressors and fans; ventilating or recycling hoods incorporating a fan" },
  { code: "8415", description: "Air conditioning machines, comprising a motor-driven fan and elements for changing the temperature and humidity, including those machines in which the humidity cannot be separately regulated" },
  { code: "8416", description: "Furnace burners for liquid fuel, for pulverised solid fuel or for gas; mechanical stokers, including their mechanical grates, mechanical ash dischargers and similar appliances" },
  { code: "8417", description: "Industrial or laboratory furnaces and ovens, including incinerators, non-electric" },
  { code: "8418", description: "Refrigerators, freezers and other refrigerating or freezing equipment, electric or other; heat pumps other than air conditioning machines of heading 8415" },
  { code: "8419", description: "Machinery, plant or laboratory equipment, whether or not electrically heated (excluding furnaces, ovens and other equipment of heading 8514), for the treatment of materials by a process involving a change of temperature" },
  { code: "8420", description: "Calendering or other rolling machines, other than for metals or glass, and cylinders therefor" },
  { code: "8421", description: "Centrifuges, including centrifugal dryers; filtering or purifying machinery and apparatus, for liquids or gases" },
  { code: "8422", description: "Dish washing machines; machinery for cleaning or drying bottles or other containers; machinery for filling, closing, sealing or labelling bottles, cans, boxes, bags or other containers; machinery for capsuling bottles, jars, tubes and similar containers; other packing or wrapping machinery (including heat-shrink wrapping machinery); machinery for aerating beverages" },
  { code: "8423", description: "Weighing machinery (excluding balances of a sensitivity of 5 cg or better), including weight-operated counting or checking machines; weighing machine weights of all kinds" },
  { code: "8424", description: "Mechanical appliances (whether or not hand-operated) for projecting, dispersing or spraying liquids or powders; fire extinguishers, whether or not charged; spray guns and similar appliances; steam or sand blasting machines and similar jet projecting machines" },
  { code: "8425", description: "Pulley tackle and hoists other than skip hoists; winches and capstans; jacks" },
  { code: "8426", description: "Ships derricks; cranes, including cable cranes; mobile lifting frames, straddle carriers and works trucks fitted with a crane" },
  { code: "8427", description: "Fork-lift trucks; other works trucks fitted with lifting or handling equipment" },
  { code: "8428", description: "Other lifting, handling, loading or unloading machinery (for example, lifts, escalators, conveyors, teleferics)" },
  { code: "8429", description: "Self-propelled bulldozers, angledozers, graders, levellers, scrapers, mechanical shovels, excavators, shovel loaders, tamping machines and road rollers" },
  { code: "8430", description: "Other moving, grading, levelling, scraping, excavating, tamping, compacting, extracting or boring machinery, for earth, minerals or ores; pile-drivers and pile-extractors; snow-ploughs and snow-blowers" },
  { code: "8431", description: "Parts suitable for use solely or principally with the machinery of headings 8425 to 8430" },
  { code: "8432", description: "Agricultural, horticultural or forestry machinery for soil preparation or cultivation; lawn or sports-ground rollers" },
  { code: "8433", description: "Harvesting or threshing machinery, including straw or fodder balers; grass or hay mowers; machines for cleaning, sorting or grading eggs, fruit or other agricultural produce, other than machinery of heading 8437" },
  { code: "8434", description: "Milking machines and dairy machinery" },
  { code: "8435", description: "Presses, crushers and similar machinery used in the manufacture of wine, cider, fruit juices or similar beverages" },
  { code: "8436", description: "Other agricultural, horticultural, forestry, poultry-keeping or bee-keeping machinery, including germination plant fitted with mechanical or thermal equipment; poultry incubators and brooders" },
  { code: "8437", description: "Machines for cleaning, sorting or grading seed, grain or dried leguminous vegetables; machinery used in the milling industry or for the working of cereals or dried leguminous vegetables" },
  { code: "8438", description: "Machinery, not specified or included elsewhere in this Chapter, for the industrial preparation or manufacture of food or drink, other than machinery for the extraction or preparation of animal or fixed vegetable fats or oils" },
  { code: "8439", description: "Machinery for making pulp of fibrous cellulosic material or for making or finishing paper or paperboard" },
  { code: "8440", description: "Bookbinding machinery, including book-sewing machines" },
  { code: "8441", description: "Other machinery for making up paper pulp, paper or paperboard, including cutting machines of all kinds" },
  { code: "8442", description: "Machinery, apparatus and equipment (other than the machine-tools of headings 8456 to 8465) for preparing or making plates, cylinders or other printing components; plates, cylinders and other printing components; plates, cylinders and lithographic stones, prepared for printing purposes" },
  { code: "8443", description: "Printing machinery used for printing by means of plates, cylinders and other printing components of heading 8442; other printers, copying machines and facsimile machines, whether or not combined; parts and accessories thereof" },
  { code: "8444", description: "Machines for extruding, drawing, texturing or cutting man-made textile materials" },
  { code: "8445", description: "Machines for preparing textile fibres; spinning, doubling or twisting machines and other machinery for producing textile yarns; textile reeling or winding (including weft-winding) machines and machines for preparing textile yarns for use on the machines of heading 8446 or 8447" },
  { code: "8446", description: "Weaving machines (looms)" },
  { code: "8447", description: "Knitting machines, stitch-bonding machines and machines for making gimped yarn, tulle, lace, embroidery, trimmings, braid or net and machines for tufting" },
  { code: "8448", description: "Auxiliary machinery for use with machines of heading 8444, 8445, 8446 or 8447 (for example, dobbies, Jacquards, automatic stop motions, shuttle changing mechanisms); parts and accessories suitable for use solely or principally with the machines of this heading or of heading 8444, 8445, 8446 or 8447 (for example, spindles and spindle flyers, card clothing, combs, extruding nipples, shuttles, healds and heald-frames, hosiery needles)" },
  { code: "8449", description: "Machinery for the manufacture or finishing of felt or nonwovens in the piece or in shapes, including machinery for making felt hats; blocks for making hats" },
  { code: "8450", description: "Household or laundry-type washing machines, including machines which both wash and dry" },
  { code: "8451", description: "Machinery (other than machines of heading 8450) for washing, cleaning, wringing, drying, ironing, pressing (including fusing presses), bleaching, dyeing, dressing, finishing, coating or impregnating textile yarns, fabrics or made up textile articles and machines for applying the paste to the base fabric or other support used in the manufacture of floor coverings such as linoleum; machines for reeling, unreeling, folding, cutting or pinking textile fabrics" },
  { code: "8452", description: "Sewing machines, other than book-sewing machines of heading 8440; furniture, bases and covers specially designed for sewing machines; sewing machine needles" },
  { code: "8453", description: "Machinery for preparing, tanning or working hides, skins or leather or for making or repairing footwear or other articles of hides, skins or leather, other than sewing machines" },
  { code: "8454", description: "Converters, ladles, ingot moulds and casting machines, of a kind used in metallurgy or in metal foundries" },
  { code: "8455", description: "Metal-rolling mills and rolls therefor" },
  { code: "8456", description: "Machine-tools for working any material by removal of material, operated by laser or other light or photon beam, ultrasonic, electro-discharge, electro-chemical, electron beam, ionic-beam or plasma arc processes; water-jet cutting machines" },
  { code: "8457", description: "Machining centres, unit construction machines (single station) and multi-station transfer machines, for working metal" },
  { code: "8458", description: "Lathes (including turning centres) for removing metal" },
  { code: "8459", description: "Machine-tools (including way-type unit head machines) for drilling, boring, milling, threading or tapping by removing metal, other than lathes (including turning centres) of heading 8458" },
  { code: "8460", description: "Machine-tools for deburring, sharpening, grinding, honing, lapping, polishing or otherwise finishing metal or cermets by means of grinding stones, abrasives or polishing products, other than gear cutting, gear grinding or gear finishing machines of heading 8461" },
  { code: "8461", description: "Machine-tools for planing, shaping, slotting, broaching, gear cutting, gear grinding or gear finishing, sawing, cutting-off and other machine-tools working by removing metal or cermets, not elsewhere specified or included" },
  { code: "8462", description: "Machine-tools (including presses) for working metal by forging, hammering or die-stamping; machine-tools (including presses) for working metal by bending, folding, straightening, flattening, shearing, punching or notching; presses for working metal or metal carbides, not specified above" },
  { code: "8463", description: "Other machine-tools for working metal or cermets, without removing material" },
  { code: "8464", description: "Machine-tools for working stone, ceramics, concrete, asbestos-cement or like mineral materials or for cold working glass" },
  { code: "8465", description: "Machine-tools (including machines for nailing, stapling, glueing or otherwise assembling) for working wood, cork, bone, hard rubber, hard plastics or similar hard materials" },
  { code: "8466", description: "Parts and accessories suitable for use solely or principally with the machines of headings 8456 to 8465, including work or tool holders, self-opening dieheads, dividing heads and other special attachments for machine-tools" },
  { code: "8467", description: "Tools for working in the hand, pneumatic, hydraulic or with self-contained electric or non-electric motor" },
  { code: "8468", description: "Machinery and apparatus for soldering, brazing or welding, whether or not capable of cutting, other than those of heading 8515; gas-operated surface tempering machines and appliances" },
  { code: "8469", description: "Typewriters other than printers of heading 8443; word-processing machines" },
  { code: "8470", description: "Calculating machines and pocket-size data recording, reproducing and displaying machines with calculating functions; accounting machines, postage-franking machines, ticket-issuing machines and similar machines, incorporating a calculating device; cash registers" },
  { code: "8471", description: "Automatic data processing machines and units thereof; magnetic or optical readers, machines for transcribing data onto data media in coded form and machines for processing such data, not elsewhere specified or included (computers, laptops, tablets)" },
  { code: "8472", description: "Other office machines (for example, hectograph or stencil duplicating machines, addressing machines, automatic banknote dispensers, coin-sorting machines, coin-counting or wrapping machines, pencil-sharpening machines, perforating or stapling machines)" },
  { code: "8473", description: "Parts and accessories (other than covers, carrying cases and the like) suitable for use solely or principally with machines of headings 8469 to 8472" },
  { code: "8474", description: "Machinery for sorting, screening, separating, washing, crushing, grinding, mixing or kneading earth, stone, ores or other mineral substances, in solid (including powder or paste) form; machinery for agglomerating, shaping or moulding solid mineral fuels, ceramic paste, unhardened cements, plastering materials or other mineral products in powder or paste form; machines for forming foundry moulds of sand" },
  { code: "8475", description: "Machines for assembling electric or electronic lamps, tubes or valves or flashbulbs, in glass envelopes; machines for manufacturing or hot working glass or glassware" },
  { code: "8476", description: "Automatic goods-vending machines (for example, postage stamp, cigarette, food or beverage machines), including money-changing machines" },
  { code: "8477", description: "Machinery for working rubber or plastics or for the manufacture of products from these materials, not specified or included elsewhere in this Chapter" },
  { code: "8478", description: "Machinery for preparing or making up tobacco, not specified or included elsewhere in this Chapter" },
  { code: "8479", description: "Machines and mechanical appliances having individual functions, not specified or included elsewhere in this Chapter" },
  { code: "8480", description: "Moulding boxes for metal foundry; mould bases; moulding patterns; moulds for metal (other than ingot moulds), for metal carbides, for glass, for mineral materials, for rubber or for plastics" },
  { code: "8481", description: "Taps, cocks, valves and similar appliances for pipes, boiler shells, tanks, vats or the like, including pressure-reducing valves and thermostatically controlled valves" },
  { code: "8482", description: "Ball or roller bearings" },
  { code: "8483", description: "Transmission shafts (including cam shafts and crank shafts) and cranks; bearing housings and plain shaft bearings; gears and gearing; ball or roller screws; gear boxes and other speed changers, including torque converters; flywheels and pulleys, including pulley blocks; clutches and shaft couplings (including universal joints)" },
  { code: "8484", description: "Gaskets and similar joints of metal sheeting combined with other material or of two or more layers of metal; sets or assortments of gaskets and similar joints, dissimilar in composition, put up in pouches, envelopes or similar packings; mechanical seals" },
  { code: "8485", description: "Machinery parts, not containing electrical connectors, insulators, coils, contacts or other electrical features, not specified or included elsewhere in this Chapter" },
  { code: "8486", description: "Machines and apparatus of a kind used solely or principally for the manufacture of semiconductor boules or wafers, semiconductor devices, electronic integrated circuits or flat panel displays" },
  { code: "8487", description: "Machinery parts, not containing electrical connectors, insulators, coils, contacts or other electrical features" },
];
export default hsnData2;
